import React, { useState, useEffect, useMemo, useCallback } from "react";
import { FaShieldAlt, FaTerminal, FaSortAmountDown, FaSortAmountUp, FaPlus, FaSync } from "react-icons/fa";
import PlaybookCard from "../components/sentinel/PlaybookCard";
import MitreTag from "../components/sentinel/MitreTag";
import RulePreview from "../components/sentinel/RulePreview";
import PlaybookViewer from "../components/sentinel/PlaybookViewer";
import ToastContainer, { useToast } from "../components/ui/ToastNotification";
import "../Styles/pages/SentinelDashboard.css";

/* Sample playbooks to preview PlaybookCard variants */
const samplePlaybooks = [
  {
    title: "Credential Dumping Response",
    severity: "critical",
    technique: "T1003.001",
    status: "approved",
    date: "2026-06-18",
    eventCount: 142,
  },
  {
    title: "Lateral Movement via SMB",
    severity: "high",
    technique: "T1021.002",
    status: "approved",
    date: "2026-06-17",
    eventCount: 87,
  },
  {
    title: "Suspicious PowerShell Execution",
    severity: "high",
    technique: "T1059.001",
    status: "draft",
    date: "2026-06-17",
    eventCount: 53,
  },
  {
    title: "DNS Tunneling Detection",
    severity: "medium",
    technique: "T1071.004",
    status: "approved",
    date: "2026-06-16",
    eventCount: 214,
  },
  {
    title: "Unusual Outbound Traffic",
    severity: "medium",
    technique: "T1048.003",
    status: "draft",
    date: "2026-06-16",
    eventCount: 31,
  },
  {
    title: "Benign Scheduled Task",
    severity: "low",
    technique: "T1053.005",
    status: "rejected",
    date: "2026-06-15",
    eventCount: 12,
  },
];

/* Sample MITRE techniques to showcase MitreTag variants */
const sampleTechniques = [
  { techniqueId: "T1110.001", techniqueName: "Password Guessing",         tactic: "credential-access" },
  { techniqueId: "T1566.001", techniqueName: "Spearphishing Attachment",  tactic: "initial-access" },
  { techniqueId: "T1059.001", techniqueName: "PowerShell",                tactic: "execution" },
  { techniqueId: "T1053.005", techniqueName: "Scheduled Task",            tactic: "persistence" },
  { techniqueId: "T1083",     techniqueName: "File and Directory Discovery", tactic: "discovery" },
  { techniqueId: "T1021.002", techniqueName: "SMB/Windows Admin Shares",  tactic: "lateral-movement" },
  { techniqueId: "T1071.004", techniqueName: "DNS",                       tactic: "command-and-control" },
  { techniqueId: "T1048.003", techniqueName: "Exfiltration Over C2",      tactic: "exfiltration" },
  { techniqueId: "T1070.004", techniqueName: "File Deletion",             tactic: "defense-evasion" },
  { techniqueId: "T1068",     techniqueName: "Exploitation for Privilege Escalation", tactic: "privilege-escalation" },
  { techniqueId: "T1486",     techniqueName: "Data Encrypted for Impact", tactic: "impact" },
  { techniqueId: "T1119",     techniqueName: "Automated Collection",      tactic: "collection" },
];

/* Rich details for PlaybookViewer modal — includes IOC tables,
   containment checkboxes, and full Sentinel-style playbook sections */
const playbookDetails = {
  "T1003.001": {
    markdownContent: `# 🛡️ OS Credential Dumping: LSASS Memory

---

| Field            | Value |
|------------------|-------|
| **Playbook ID**  | \`PB-LSASS-DUMP-001\` |
| **Version**      | \`1.0.0\` |
| **Severity**     | 🔴 **CRITICAL** |
| **Classification** | \`TLP:RED\` |
| **Attack Pattern** | \`credential_dumping\` |
| **Generated At** | \`2026-06-18T14:23:00Z\` |
| **Generated By** | \`PhantomNet Sentinel – PlaybookGenerator v1.0\` |
| **Status**       | \`ACTIVE\` |

---

## 📋 Summary

> **Campaign Overview:** LSASS memory dumping detected on endpoint \`WS-FIN-042\`. The attacker used \`procdump.exe\` to extract credential material from the LSASS process. Immediate credential rotation required.

### Trigger Context

| Property            | Value |
|---------------------|-------|
| **Trigger Type**    | \`process_anomaly\` |
| **Trigger Condition** | \`procdump.exe targeting lsass.exe\` |
| **Detection Time**  | \`2026-06-18T14:23:00Z\` |
| **Source IP**       | \`10.0.3.42\` |
| **Target IP**       | \`10.0.1.15\` |

### Incident Priority

| Dimension       | Assessment |
|-----------------|------------|
| **Confidentiality Impact** | Critical |
| **Integrity Impact**       | High |
| **Availability Impact**    | Medium |
| **Blast Radius**           | Domain-wide credential exposure |

---

## 🔍 Indicators of Compromise (IOCs)

### Source IPs

| IP Address | Port(s) | Protocol | Hit Count | Threat Intel | First Seen | Last Seen |
|------------|---------|----------|-----------|--------------|------------|-----------|
| \`10.0.3.42\` | \`445, 135\` | \`TCP\` | \`37\` | 🔴 Known C2 Node | \`2026-06-18T12:01:00Z\` | \`2026-06-18T14:23:00Z\` |
| \`192.168.1.105\` | \`3389\` | \`TCP\` | \`12\` | 🟡 Suspicious | \`2026-06-18T13:45:00Z\` | \`2026-06-18T14:20:00Z\` |

### Additional IOC Hashes

| Hash Type | Value |
|-----------|-------|
| \`SHA256\` | \`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\` |
| \`MD5\` | \`d41d8cd98f00b204e9800998ecf8427e\` |

---

## 🎯 MITRE ATT&CK Mapping

| Technique ID | Technique Name | Tactic | Sub-technique | Description |
|---|---|---|---|---|
| [T1003](https://attack.mitre.org/techniques/T1003/) | **OS Credential Dumping** | Credential Access | T1003.001 – LSASS Memory | Adversary dumped LSASS process memory to extract credentials. |
| [T1078](https://attack.mitre.org/techniques/T1078/) | **Valid Accounts** | Defense Evasion, Persistence | — | Compromised credentials may be used to maintain access. |
| [T1021](https://attack.mitre.org/techniques/T1021/) | **Remote Services** | Lateral Movement | T1021.002 – SMB | Dumped credentials enable lateral movement via SMB. |

> 📖 Reference: [MITRE ATT&CK Enterprise Matrix](https://attack.mitre.org/matrices/enterprise/)

---

## 🚨 Containment Steps

> **⚡ Execute steps in order. Mark each checkbox as complete. Escalate immediately if any step fails.**

### Phase 1 – Immediate Isolation (T+0 to T+5 min)

- [ ] **Isolate compromised endpoint** – Network-isolate \`WS-FIN-042\` (10.0.3.42) immediately via EDR or switch ACL.
- [ ] **Kill malicious process** – Terminate \`procdump.exe\` and any child processes on the target host.
- [ ] **Block attacker IP** – Apply ACL rule to block \`10.0.3.42\` on all perimeter devices.
- [ ] **Invalidate sessions** – Force-expire all active sessions for accounts on \`WS-FIN-042\`.

### Phase 2 – Investigation (T+5 to T+30 min)

- [ ] **Capture memory dump** – Collect full memory image from \`WS-FIN-042\` for forensic analysis.
- [ ] **Pull authentication logs** – Retrieve the last 24 hours of auth logs from AD and SIEM.
- [ ] **Check for lateral movement** – Search SIEM for successful logons from \`10.0.3.42\` to other hosts.
- [ ] **Query threat intelligence** – Submit IOC hashes and IPs to VirusTotal and AbuseIPDB.

### Phase 3 – Remediation & Hardening (T+30 min onward)

- [ ] **Reset all compromised credentials** – Force password reset for all accounts accessed from \`WS-FIN-042\`.
- [ ] **Rotate krbtgt keys** – Force rotation of Active Directory krbtgt account keys (twice).
- [ ] **Enable LSA Protection** – Deploy \`RunAsPPL\` via Group Policy to all endpoints.
- [ ] **Implement Credential Guard** – Enable Credential Guard on supported Windows editions.
- [ ] **Create incident ticket** – Open ticket in Jira: *"LSASS Credential Dump: WS-FIN-042"*.

---

## 📁 Artifacts & Rule References

### Detection Rules

| Rule ID | Rule Name | Source | Status |
|---------|-----------|--------|--------|
| \`RULE-CRED-001\` | LSASS Memory Dump Detection | \`PhantomNet SIEM\` | ✅ Active |
| \`RULE-CRED-002\` | Procdump Execution Alert | \`Windows Defender\` | ✅ Active |

### Log Sources

| Source | Path / Index | Retention |
|--------|--------------|-----------|
| **Auth Logs**      | \`/var/log/auth.log\`       | \`90 days\` |
| **Network Traffic**| \`netflow-*\`               | \`90 days\` |
| **SIEM Alerts**    | \`siem-alerts-*\`           | \`90 days\` |

---

*This playbook was auto-generated by **PhantomNet Sentinel** · [https://github.com/sriram21-09/PhantomNet](https://github.com/sriram21-09/PhantomNet)*`,
    snortRule: `alert tcp $EXTERNAL_NET any -> $HOME_NET 445 (msg:"ET EXPLOIT Possible LSASS Dump over SMB"; flow:to_server,established; content:"|ff|SMB"; depth:4; content:"lsass"; nocase; sid:2024003; rev:1;)`,
    sigmaRule: `title: LSASS Memory Dumping via Procdump
id: ffa81d86-063a-4a87-bf71-3246a1e8e1d5
status: stable
description: Detects procdump writing to lsass memory
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    CommandLine|contains:
      - 'procdump'
      - 'lsass'
  condition: selection
level: critical`
  },
  "T1021.002": {
    markdownContent: `# 🛡️ Lateral Movement: SMB/Windows Admin Shares

---

| Field            | Value |
|------------------|-------|
| **Playbook ID**  | \`PB-SMB-LATERAL-001\` |
| **Severity**     | 🟠 **HIGH** |
| **Classification** | \`TLP:AMBER\` |
| **Attack Pattern** | \`lateral_movement_smb\` |
| **Generated At** | \`2026-06-17T09:45:00Z\` |

---

## 📋 Summary

> **Campaign Overview:** Lateral movement via SMB detected from \`SRV-DC-01\` to multiple workstations. The attacker leveraged ADMIN$ share access with compromised domain admin credentials.

---

## 🔍 Indicators of Compromise (IOCs)

### Source IPs

| IP Address | Port(s) | Protocol | Hit Count | Threat Intel | First Seen | Last Seen |
|------------|---------|----------|-----------|--------------|------------|-----------|
| \`10.0.1.10\` | \`445\` | \`TCP\` | \`89\` | ❓ Internal | \`2026-06-17T08:30:00Z\` | \`2026-06-17T09:45:00Z\` |
| \`10.0.1.10\` | \`139\` | \`TCP\` | \`23\` | ❓ Internal | \`2026-06-17T09:00:00Z\` | \`2026-06-17T09:42:00Z\` |
| \`10.0.2.55\` | \`445\` | \`TCP\` | \`7\` | 🟡 Suspicious | \`2026-06-17T09:15:00Z\` | \`2026-06-17T09:40:00Z\` |

---

## 🎯 MITRE ATT&CK Mapping

| Technique ID | Technique Name | Tactic | Sub-technique | Description |
|---|---|---|---|---|
| [T1021](https://attack.mitre.org/techniques/T1021/) | **Remote Services** | Lateral Movement | T1021.002 – SMB/Admin Shares | Adversary used SMB to access ADMIN$ on target workstations. |
| [T1078](https://attack.mitre.org/techniques/T1078/) | **Valid Accounts** | Defense Evasion | T1078.002 – Domain Accounts | Compromised domain admin credentials were used. |

---

## 🚨 Containment Steps

> **⚡ Execute steps in order. Mark each checkbox as complete.**

### Phase 1 – Immediate Containment (T+0 to T+5 min)

- [ ] **Block outbound SMB** – Block port 445/139 from source host \`10.0.1.10\` on all segments.
- [ ] **Revoke sessions** – Force-expire all active SMB and user sessions on target machines.
- [ ] **Disable compromised account** – Temporarily disable domain admin account used in the attack.

### Phase 2 – Investigation (T+5 to T+30 min)

- [ ] **Review Event ID 4624** – Search for Logon Type 3 events from \`10.0.1.10\` across all endpoints.
- [ ] **Verify credential exposure** – Determine which credentials were used to authenticate via SMB.
- [ ] **Check for persistence** – Scan target machines for scheduled tasks, services, or startup items created by the attacker.

### Phase 3 – Remediation (T+30 min onward)

- [ ] **Deploy LAPS** – Restrict local admin account reuse across machines with LAPS.
- [ ] **Enable SMB signing** – Require SMB signing and encryption on all domain systems.
- [ ] **Block lateral SMB** – Implement host firewall rules to block endpoint-to-endpoint SMB.

---

*This playbook was auto-generated by **PhantomNet Sentinel***`,
    snortRule: `alert tcp $HOME_NET any -> $HOME_NET 445 (msg:"INTERNAL Lateral Movement via SMB Share"; flow:to_server,established; content:"|5c 00 41 00 44 00 4d 00 49 00 4e 00 24|"; msg:"Access to ADMIN$ share"; sid:2024004; rev:1;)`,
    sigmaRule: `title: SMB Lateral Movement Logon
id: cba72186-063a-4a87-bf71-3246a1e8e1d5
status: stable
description: Detects remote lateral movement logons via SMB
logsource:
  category: authentication
  product: windows
detection:
  selection:
    EventID: 4624
    LogonType: 3
    IpAddress|not: '127.0.0.1'
  condition: selection
level: high`
  },
  "T1059.001": {
    markdownContent: `# 🛡️ Execution: PowerShell Download Cradle

---

| Field            | Value |
|------------------|-------|
| **Playbook ID**  | \`PB-PS-CRADLE-001\` |
| **Severity**     | 🟠 **HIGH** |
| **Classification** | \`TLP:AMBER\` |
| **Attack Pattern** | \`powershell_download_cradle\` |
| **Generated At** | \`2026-06-17T16:12:00Z\` |

---

## 📋 Summary

> **Campaign Overview:** A PowerShell download cradle was detected executing on workstation \`WS-DEV-019\`. The script attempted to download and execute a second-stage payload from an external C2 server.

---

## 🔍 Indicators of Compromise (IOCs)

### Source IPs

| IP Address | Port(s) | Protocol | Hit Count | Threat Intel | First Seen | Last Seen |
|------------|---------|----------|-----------|--------------|------------|-----------|
| \`45.33.32.156\` | \`443\` | \`TCP\` | \`3\` | 🔴 Known C2 | \`2026-06-17T16:10:00Z\` | \`2026-06-17T16:12:00Z\` |

### Domain / URL IOCs

| Domain / URL | Resolved IP | Category |
|---|---|---|
| \`evil-payload.darksite.cc\` | \`45.33.32.156\` | \`Malware Distribution\` |
| \`cdn-update.malware.xyz\` | \`45.33.32.157\` | \`C2 Infrastructure\` |

---

## 🎯 MITRE ATT&CK Mapping

| Technique ID | Technique Name | Tactic | Sub-technique | Description |
|---|---|---|---|---|
| [T1059](https://attack.mitre.org/techniques/T1059/) | **Command and Scripting Interpreter** | Execution | T1059.001 – PowerShell | PowerShell used to download and execute payload. |
| [T1105](https://attack.mitre.org/techniques/T1105/) | **Ingress Tool Transfer** | Command and Control | — | External payload downloaded via HTTPS. |

---

## 🚨 Containment Steps

> **⚡ Execute steps in order. Mark each checkbox as complete.**

### Phase 1 – Immediate Response (T+0 to T+5 min)

- [ ] **Kill PowerShell process** – Terminate \`powershell.exe\` and any child processes on \`WS-DEV-019\`.
- [ ] **Block C2 domain** – Add \`evil-payload.darksite.cc\` and \`cdn-update.malware.xyz\` to DNS sinkhole.
- [ ] **Block C2 IP** – Firewall block \`45.33.32.156\` and \`45.33.32.157\` on all egress points.
- [ ] **Isolate endpoint** – Network-isolate \`WS-DEV-019\` via EDR.

### Phase 2 – Investigation (T+5 to T+30 min)

- [ ] **Reconstruct command** – Extract full command from PowerShell transcript and Script Block logs.
- [ ] **Check for downloaded payloads** – Scan temp directories, Downloads folder, and AppData for dropped files.
- [ ] **Verify network connections** – Review all outbound connections from \`WS-DEV-019\` in the last 2 hours.

### Phase 3 – Hardening (T+30 min onward)

- [ ] **Enable Constrained Language Mode** – Enforce CLM via Group Policy across all endpoints.
- [ ] **Deploy AppLocker rules** – Block unauthorized PowerShell script execution.
- [ ] **Enable Script Block Logging** – Ensure all PowerShell activity is logged for future detection.

---

*This playbook was auto-generated by **PhantomNet Sentinel***`,
    snortRule: `alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg:"EXTERNAL PowerShell User-Agent Detected"; flow:to_server,established; content:"WindowsPowerShell"; http_header; sid:2024005; rev:1;)`,
    sigmaRule: `title: Suspicious PowerShell Download Cradle
id: 3b6ab547-1c3b-4a85-bf71-3246a1e8e1d5
status: experimental
description: Detects suspicious PowerShell download cradle patterns
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    CommandLine|contains|all:
      - 'powershell'
      - 'downloadstring'
  condition: selection
level: high`
  },
  "T1071.004": {
    markdownContent: `# 🛡️ Command and Control: DNS Tunneling Detection

---

| Field            | Value |
|------------------|-------|
| **Playbook ID**  | \`PB-DNS-TUNNEL-001\` |
| **Severity**     | 🟡 **MEDIUM** |
| **Classification** | \`TLP:AMBER\` |
| **Attack Pattern** | \`dns_tunneling\` |
| **Generated At** | \`2026-06-16T22:05:00Z\` |

---

## 📋 Summary

> **Campaign Overview:** Anomalous DNS query patterns detected from endpoint \`WS-NET-007\`. High-entropy subdomain requests suggest DNS tunneling for data exfiltration or C2 communication.

---

## 🔍 Indicators of Compromise (IOCs)

### Source IPs

| IP Address | Port(s) | Protocol | Hit Count | Threat Intel | First Seen | Last Seen |
|------------|---------|----------|-----------|--------------|------------|-----------|
| \`10.0.5.22\` | \`53\` | \`UDP\` | \`214\` | ❓ Internal | \`2026-06-16T20:00:00Z\` | \`2026-06-16T22:05:00Z\` |

### Domain / URL IOCs

| Domain / URL | Resolved IP | Category |
|---|---|---|
| \`a1b2c3d4e5f6.tunnel.darkdns.io\` | \`198.51.100.42\` | \`DNS Tunneling C2\` |
| \`x7y8z9.exfil.darkdns.io\` | \`198.51.100.42\` | \`Data Exfiltration\` |

---

## 🚨 Containment Steps

> **⚡ Execute steps in order. Mark each checkbox as complete.**

### Phase 1 – Immediate Capture (T+0 to T+5 min)

- [ ] **Start packet capture** – Begin PCAP on all interfaces facing \`10.0.5.22\` for 300 seconds.
- [ ] **DNS Sinkhole** – Route \`*.darkdns.io\` to a local sinkhole immediately.
- [ ] **Isolate endpoint** – Quarantine \`WS-NET-007\` from the network.
- [ ] **Rate-limit DNS** – Apply rate-limit: max 10 DNS queries/sec from \`10.0.5.22\`.

### Phase 2 – Investigation (T+5 to T+30 min)

- [ ] **Analyse DNS patterns** – Inspect TXT, CNAME, and NULL query types for encoded payloads.
- [ ] **Calculate entropy** – Measure subdomain entropy to confirm tunneling vs legitimate traffic.
- [ ] **Query threat intel** – Look up \`darkdns.io\` and \`198.51.100.42\` in threat feeds.

### Phase 3 – Remediation (T+30 min onward)

- [ ] **Block direct DNS** – Force all DNS through corporate resolvers; block port 53 at egress.
- [ ] **Deploy DNS filtering** – Enable DNS filtering with query rate-limiting.
- [ ] **Update IDS signatures** – Add DNS tunneling fingerprint to IDS/IPS.

---

*This playbook was auto-generated by **PhantomNet Sentinel***`,
    snortRule: `alert udp $HOME_NET any -> $EXTERNAL_NET 53 (msg:"EXTERNAL High Rate DNS Queries (Tunneling)"; content:"|00 00 10 00 01|"; threshold:type threshold, track by_src, count 100, seconds 5; sid:2024006; rev:1;)`,
    sigmaRule: `title: DNS Tunneling Pattern Detection
id: 116ab547-1c3b-4a85-bf71-3246a1e8e1d5
status: experimental
description: Detects unusual DNS TXT query rates indicative of tunneling
logsource:
  category: dns
detection:
  selection:
    QueryType: TXT
    QueryLength|gt: 100
  condition: selection
level: high`
  }
};

const defaultDetails = {
  markdownContent: `# 🛡️ Threat Playbook

---

| Field            | Value |
|------------------|-------|
| **Playbook ID**  | \`PB-GENERIC-001\` |
| **Severity**     | 🟡 **MEDIUM** |
| **Classification** | \`TLP:GREEN\` |
| **Generated By** | \`PhantomNet Sentinel\` |

---

## 📋 Summary

> **Campaign Overview:** General mitigation and response strategy for the specified threat. Review the checklist below and execute containment steps as needed.

---

## 🔍 Indicators of Compromise (IOCs)

> ⚠️ No specific IOCs captured yet. Run forensic scan to enumerate artefacts.

---

## 🚨 Containment Steps

> **⚡ Execute steps in order. Mark each checkbox as complete.**

- [ ] **Review system access logs** – Check all logs for the affected time window.
- [ ] **Verify firewall configurations** – Confirm endpoint firewall rules are current.
- [ ] **Conduct credential sweep** – Run full credential audit on the host.
- [ ] **Re-run vulnerability scan** – Execute a comprehensive vulnerability scan on the endpoint.
- [ ] **Update detection rules** – Review and update SIEM detection rules based on findings.
- [ ] **Document findings** – Record all investigation results in the incident management system.

---

*This playbook was auto-generated by **PhantomNet Sentinel***`,
  snortRule: `alert tcp $EXTERNAL_NET any -> $HOME_NET any (msg:"SUSPICIOUS General Network Activity"; flow:to_server,established; sid:2024999; rev:1;)`,
  sigmaRule: `title: General Suspicious Activity Detection
id: efa82186-063a-4a87-bf71-3246a1e8e1d5
status: experimental
description: Detects generic suspicious behavior indicators
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    CommandLine|contains: 'suspicious_command'
  condition: selection
level: medium`
};

/* Sample detection rules */
const sampleSnortRule = `alert tcp $EXTERNAL_NET any -> $HOME_NET 445 (msg:"ET EXPLOIT Possible SMB Brute Force"; flow:to_server,established; content:"|ff|SMB"; depth:4; content:"|73 00 00 00|"; distance:0; threshold:type both, track by_src, count 5, seconds 60; classtype:attempted-admin; sid:2024001; rev:3;)

# Secondary detection for lateral movement
alert tcp $HOME_NET any -> $HOME_NET 135 (msg:"INTERNAL Lateral Movement via DCOM"; flow:to_server,established; content:"|05|"; depth:1; content:"|0b|"; distance:1; within:1; classtype:attempted-admin; sid:2024002; rev:1;)`;

const sampleSigmaRule = `title: Suspicious PowerShell Download Cradle
id: 3b6ab547-1c3b-4a85-bf71-3246a1e8e1d5
status: experimental
description: Detects suspicious PowerShell download cradle patterns
author: PhantomNet Sentinel
date: 2026/06/18
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    CommandLine|contains|all:
      - 'powershell'
      - 'downloadstring'
  condition: selection
falsepositives:
  - Legitimate admin scripts
level: high
tags:
  - attack.execution
  - attack.t1059.001`;

/* ═══════════════════════════════════════════════════════════════
   Sort Configuration
   ═══════════════════════════════════════════════════════════════ */

const SEVERITY_ORDER = { critical: 4, high: 3, medium: 2, low: 1 };
const STATUS_ORDER = { draft: 1, approved: 2, rejected: 3 };

const SORT_COLUMNS = [
  { key: "date", label: "Date" },
  { key: "severity", label: "Severity" },
  { key: "status", label: "Status" },
];

const SentinelDashboard = () => {
  const [playbooks, setPlaybooks] = useState([]);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [activeTab, setActiveTab] = useState("all");

  const [selectedPlaybook, setSelectedPlaybook] = useState(null);
  const [isViewerOpen, setIsViewerOpen] = useState(false);
  const [loadingDetails, setLoadingDetails] = useState(false);

  const [techniques, setTechniques] = useState(sampleTechniques);

  /* ── Sort State ── */
  const [sortColumn, setSortColumn] = useState("date");
  const [sortDirection, setSortDirection] = useState("desc"); // newest first

  /* ── Toast Notifications ── */
  const { toasts, addToast, removeToast } = useToast();

  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      // 1. Fetch playbooks list
      const playbooksRes = await fetch("/api/sentinel/playbooks?limit=100");
      const playbooksData = await playbooksRes.json();
      if (!playbooksRes.ok) {
        throw new Error(playbooksData.detail || "Failed to load playbooks from server");
      }
      setPlaybooks(playbooksData.playbooks || []);

      // 2. Fetch stats
      try {
        const statsRes = await fetch("/api/sentinel/stats");
        const statsData = await statsRes.json();
        if (statsRes.ok && statsData.status === "success") {
          setStats(statsData);
        }
      } catch (statsErr) {
        console.warn("Could not fetch Sentinel stats:", statsErr);
      }

      // 3. Fetch MITRE mappings dynamically
      try {
        const techRes = await fetch("/api/sentinel/mitre/mapping");
        const techData = await techRes.json();
        if (techRes.ok && techData.status === "success" && techData.mappings) {
          const mapped = techData.mappings.map((m) => ({
            techniqueId: m.technique_id,
            techniqueName: m.technique_name,
            tactic: m.tactic,
          }));
          // Dedup
          const unique = Array.from(
            new Map(mapped.map((item) => [item.techniqueId, item])).values()
          );
          if (unique.length > 0) {
            setTechniques(unique);
          }
        }
      } catch (techErr) {
        console.warn("Could not fetch MITRE mappings dynamically, using fallback:", techErr);
      }

    } catch (err) {
      console.error("Dashboard connection error:", err);
      setError(err.message || "Failed to connect to the Sentinel Security Service");
      addToast({
        type: "error",
        title: "Connection Failed",
        message: err.message || "Failed to connect to the Sentinel Security Service",
        duration: 6000,
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  // Normalization logic
  const getNormalizedStatus = (status) => {
    const s = status ? status.toLowerCase() : "";
    if (s === "pending") return "draft";
    if (s === "exported") return "approved";
    return s; // "approved" or "rejected"
  };

  // Filter playbooks based on tab selection
  const filteredPlaybooks = useMemo(() => {
    if (activeTab === "all") return playbooks;
    return playbooks.filter(
      (pb) => getNormalizedStatus(pb.status) === activeTab
    );
  }, [playbooks, activeTab]);

  /* ── Sort toggle handler ── */
  const handleSortClick = useCallback((column) => {
    setSortColumn((prev) => {
      if (prev === column) {
        setSortDirection((d) => (d === "asc" ? "desc" : "asc"));
        return prev;
      }
      setSortDirection(column === "date" ? "desc" : "asc");
      return column;
    });
  }, []);

  /* ── Sorted playbooks ── */
  const sortedPlaybooks = useMemo(() => {
    const list = [...filteredPlaybooks];
    const dir = sortDirection === "asc" ? 1 : -1;

    list.sort((a, b) => {
      switch (sortColumn) {
        case "date": {
          const da = a.created_at || "";
          const db = b.created_at || "";
          return dir * da.localeCompare(db);
        }
        case "severity": {
          const sa = SEVERITY_ORDER[getPlaybookSeverity(a)] || 0;
          const sb = SEVERITY_ORDER[getPlaybookSeverity(b)] || 0;
          return dir * (sa - sb);
        }
        case "status": {
          const sta = STATUS_ORDER[getNormalizedStatus(a.status)] || 0;
          const stb = STATUS_ORDER[getNormalizedStatus(b.status)] || 0;
          return dir * (sta - stb);
        }
        default:
          return 0;
      }
    });

    return list;
  }, [filteredPlaybooks, sortColumn, sortDirection]);

  // Compute tab counts
  const counts = useMemo(() => {
    let draft = 0;
    let approved = 0;
    let rejected = 0;
    playbooks.forEach((pb) => {
      const s = getNormalizedStatus(pb.status);
      if (s === "draft") draft++;
      else if (s === "approved") approved++;
      else if (s === "rejected") rejected++;
    });
    return {
      all: playbooks.length,
      draft,
      approved,
      rejected,
    };
  }, [playbooks]);

  // Map playbooks technique/score to UI severity
  const TECHNIQUE_SEVERITIES = {
    "T1003.001": "critical",
    "T1021.002": "high",
    "T1059.001": "high",
    "T1071.004": "medium",
    "T1053.005": "low",
  };

  const getPlaybookSeverity = (pb) => {
    if (pb.technique_id && TECHNIQUE_SEVERITIES[pb.technique_id]) {
      return TECHNIQUE_SEVERITIES[pb.technique_id];
    }
    const score = pb.threat_score || 0;
    if (score >= 90) return "critical";
    if (score >= 70) return "high";
    if (score >= 40) return "medium";
    return "low";
  };

  const handleCardClick = async (pb) => {
    // Open immediately with summary props to provide instant response
    setSelectedPlaybook({
      ...pb,
      playbook_content: "",
      snort_rule: "",
      sigma_rule: "",
    });
    setIsViewerOpen(true);
    setLoadingDetails(true);

    try {
      const response = await fetch(`/api/sentinel/playbooks/${pb.id}`);
      const data = await response.json();
      if (response.ok && data.status === "success") {
        setSelectedPlaybook(data.playbook);
      } else {
        console.error("Failed to load playbook details:", data.detail);
        addToast({
          type: "error",
          title: "Playbook Load Failed",
          message: data.detail || "Failed to load playbook details",
        });
      }
    } catch (err) {
      console.error("Failed to fetch playbook details:", err);
      addToast({
        type: "error",
        title: "Network Error",
        message: "Could not reach the Sentinel API. Please check your connection.",
      });
    } finally {
      setLoadingDetails(false);
    }
  };

  const handleStatusChange = (newStatus) => {
    // 1. Update playbooks list
    setPlaybooks((prev) =>
      prev.map((pb) =>
        pb.id === selectedPlaybook.id ? { ...pb, status: newStatus } : pb
      )
    );
    // 2. Update stats count
    setStats((prev) => {
      if (!prev) return prev;
      const oldStatus = selectedPlaybook.status;
      const countsUpdate = { ...prev };
      
      const oldNorm = getNormalizedStatus(oldStatus);
      const newNorm = getNormalizedStatus(newStatus);
      
      if (oldNorm !== newNorm) {
        if (oldNorm === "draft" && countsUpdate.pending > 0) countsUpdate.pending--;
        else if (oldNorm === "approved" && countsUpdate.approved > 0) countsUpdate.approved--;
        else if (oldNorm === "rejected" && countsUpdate.rejected > 0) countsUpdate.rejected--;

        if (newNorm === "draft") countsUpdate.pending++;
        else if (newNorm === "approved") countsUpdate.approved++;
        else if (newNorm === "rejected") countsUpdate.rejected++;
      }
      return countsUpdate;
    });
    // 3. Update selectedPlaybook details status so modal re-renders
    setSelectedPlaybook((prev) =>
      prev ? { ...prev, status: newStatus } : null
    );
  };

  return (
    <div className="sentinel-wrapper">
      {/* Header */}
      <div className="sentinel-header">
        <div className="sentinel-badge hud-font">SENTINEL_ENGINE_V1.0</div>
        <h1 className="sentinel-title">Sentinel Dashboard</h1>
        <p className="sentinel-subtitle">
          AUTONOMOUS THREAT DETECTION &amp; RESPONSE COMMAND CENTER
        </p>
      </div>

      {/* Live Status Bar */}
      <div className="sentinel-status-bar">
        <div className="status-item">
          <span className="status-dot-live"></span>
          <span className="status-label">ENGINE STATUS:</span>
          <span>ONLINE</span>
        </div>
        <div className="status-item">
          <span className="status-label">UPTIME:</span>
          <span>ONLINE</span>
        </div>
        <div className="status-item">
          <span className="status-label">RULES LOADED:</span>
          <span>{stats?.total_playbooks ?? playbooks.length}</span>
        </div>
        <div className="status-item">
          <span className="status-label">LAST SCAN:</span>
          <span>
            {stats?.latest_playbook_at
              ? new Date(stats.latest_playbook_at).toLocaleTimeString()
              : "—"}
          </span>
        </div>
      </div>

      {/* MITRE ATT&CK Techniques */}
      <div className="sentinel-content" style={{ marginBottom: "2rem" }}>
        <div className="sentinel-section-header">
          <h2 className="sentinel-section-title">ATT&amp;CK Coverage</h2>
          <span className="sentinel-section-count hud-font">
            {techniques.length} TECHNIQUES
          </span>
        </div>
        <div className="sentinel-mitre-grid">
          {techniques.map((t, idx) => (
            <MitreTag key={idx} {...t} />
          ))}
        </div>
      </div>

      {/* Rule Preview */}
      <div className="sentinel-content" style={{ marginBottom: "2rem" }}>
        <div className="sentinel-section-header">
          <h2 className="sentinel-section-title">Detection Rules</h2>
          <span className="sentinel-section-count hud-font">SNORT / SIGMA</span>
        </div>
        <RulePreview snortRule={sampleSnortRule} sigmaRule={sampleSigmaRule} />
      </div>

      {/* Playbook Section */}
      <div className="sentinel-content">
        <div className="sentinel-section-header">
          <h2 className="sentinel-section-title">Generated Playbooks</h2>
          <span className="sentinel-section-count hud-font">
            {filteredPlaybooks.length} PLAYBOOKS
          </span>
        </div>

        {/* Filter Tabs */}
        <div className="sentinel-tabs-container hud-font">
          <button
            className={`sentinel-tab-btn ${activeTab === "all" ? "active" : ""}`}
            onClick={() => setActiveTab("all")}
          >
            All <span className="tab-count">{counts.all}</span>
          </button>
          <button
            className={`sentinel-tab-btn ${activeTab === "draft" ? "active" : ""}`}
            onClick={() => setActiveTab("draft")}
          >
            Draft <span className="tab-count">{counts.draft}</span>
          </button>
          <button
            className={`sentinel-tab-btn ${activeTab === "approved" ? "active" : ""}`}
            onClick={() => setActiveTab("approved")}
          >
            Approved <span className="tab-count">{counts.approved}</span>
          </button>
          <button
            className={`sentinel-tab-btn ${activeTab === "rejected" ? "active" : ""}`}
            onClick={() => setActiveTab("rejected")}
          >
            Rejected <span className="tab-count">{counts.rejected}</span>
          </button>
        </div>

        {/* ── Sort Header Bar ── */}
        {!loading && !error && filteredPlaybooks.length > 0 && (
          <div className="sentinel-sort-bar hud-font">
            <span className="sort-bar-label">SORT BY:</span>
            {SORT_COLUMNS.map((col) => {
              const isActive = sortColumn === col.key;
              return (
                <button
                  key={col.key}
                  className={`sort-header-btn ${isActive ? "active" : ""}`}
                  onClick={() => handleSortClick(col.key)}
                  title={`Sort by ${col.label}`}
                >
                  {col.label}
                  {isActive && (
                    <span className="sort-arrow">
                      {sortDirection === "asc" ? (
                        <FaSortAmountUp className="sort-arrow-icon" />
                      ) : (
                        <FaSortAmountDown className="sort-arrow-icon" />
                      )}
                    </span>
                  )}
                </button>
              );
            })}
          </div>
        )}

        {/* Display Grid States */}
        {loading ? (
          <div className="sentinel-playbook-grid">
            {Array.from({ length: 6 }).map((_, idx) => (
              <div key={idx} className="playbook-skeleton-card">
                <div className="playbook-skeleton-glow"></div>
              </div>
            ))}
          </div>
        ) : error ? (
          <div className="sentinel-error-state hud-font">
            <FaTerminal className="error-icon" />
            <h3>System Connection Failure</h3>
            <p>{error}</p>
            <button onClick={fetchData} className="retry-btn">
              <FaSync style={{ marginRight: "0.5rem" }} />
              Retry Connection
            </button>
          </div>
        ) : filteredPlaybooks.length === 0 ? (
          <div className="sentinel-empty-state">
            <div className="sentinel-empty-icon">
              <FaShieldAlt />
            </div>
            <h3 className="sentinel-empty-title">No Playbooks Found</h3>
            <p className="sentinel-empty-description">
              {activeTab === "all"
                ? "No response playbooks have been generated yet. Trigger the Sentinel pipeline to create your first automated playbook."
                : `No playbooks with status "${activeTab.toUpperCase()}" found.`}
            </p>
            {activeTab === "all" ? (
              <button className="sentinel-cta-btn" onClick={fetchData}>
                <FaPlus style={{ marginRight: "0.5rem" }} />
                Refresh Playbooks
              </button>
            ) : (
              <button
                className="sentinel-cta-btn"
                onClick={() => setActiveTab("all")}
              >
                View All Playbooks
              </button>
            )}
          </div>
        ) : (
          <div className="sentinel-playbook-grid">
            {sortedPlaybooks.map((pb) => (
              <PlaybookCard
                key={pb.id}
                title={pb.playbook_name || "Untitled Playbook"}
                severity={getPlaybookSeverity(pb)}
                technique={pb.technique_id || "T0000"}
                status={getNormalizedStatus(pb.status)}
                date={pb.created_at ? pb.created_at.substring(0, 10) : "—"}
                eventCount={Math.floor((pb.threat_score || 50) * 1.5) || 1}
                onClick={() => handleCardClick(pb)}
              />
            ))}
          </div>
        )}
      </div>

      {/* Playbook Viewer Modal */}
      {selectedPlaybook && (
        <PlaybookViewer
          key={`${selectedPlaybook.id}-${isViewerOpen}`}
          isOpen={isViewerOpen}
          onClose={() => setIsViewerOpen(false)}
          id={selectedPlaybook.id}
          status={selectedPlaybook.status}
          onStatusChange={handleStatusChange}
          isLoading={loadingDetails}
          title={selectedPlaybook.playbook_name || "Untitled Playbook"}
          severity={getPlaybookSeverity(selectedPlaybook)}
          technique={selectedPlaybook.technique_id || "T0000"}
          date={selectedPlaybook.created_at ? selectedPlaybook.created_at.substring(0, 10) : "—"}
          playbook_content={selectedPlaybook.playbook_content}
          snortRule={selectedPlaybook.snort_rule}
          sigmaRule={selectedPlaybook.sigma_rule}
        />
      )}

      {/* ── Toast Notifications ── */}
      <ToastContainer toasts={toasts} onDismiss={removeToast} />
    </div>
  );
};

export default SentinelDashboard;

