"""
backend/sentinel/email_notifier.py
-------------------------------------
PhantomNet Sentinel Layer — Email Alert Dispatcher

Sends email notifications when high-severity (CRITICAL or HIGH) playbooks
are automatically generated by the Sentinel pipeline.

Features
--------
  - HTML email template with playbook title, severity, summary, and
    direct dashboard link.
  - Async dispatch via background threads to avoid blocking the main
    pipeline.
  - Integrates with SystemConfig settings from sentinel_config.py for
    SMTP credentials and recipient lists.
  - Graceful fallback: if email is disabled or SMTP is misconfigured,
    the pipeline continues without interruption.

Configuration (Environment Variables)
--------------------------------------
  SENTINEL_EMAIL_ALERTS_ENABLED     : Master switch for email alerts (default: false)
  SENTINEL_EMAIL_SMTP_HOST          : SMTP server hostname (default: localhost)
  SENTINEL_EMAIL_SMTP_PORT          : SMTP server port (default: 587)
  SENTINEL_EMAIL_SMTP_USER          : SMTP authentication username
  SENTINEL_EMAIL_SMTP_PASSWORD      : SMTP authentication password
  SENTINEL_EMAIL_SMTP_USE_TLS       : Enable STARTTLS (default: true)
  SENTINEL_EMAIL_FROM_ADDRESS       : Sender email address
  SENTINEL_EMAIL_RECIPIENTS         : Comma-separated list of recipient emails
  SENTINEL_EMAIL_SEVERITY_THRESHOLD : Minimum severity to trigger (default: CRITICAL)
  SENTINEL_DASHBOARD_BASE_URL       : Base URL for dashboard deep links

Phase 5, Week 5 — Email Alert Notifications
"""

from __future__ import annotations

import logging
import smtplib
import threading
import asyncio
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, List, Optional

logger = logging.getLogger("sentinel.email_notifier")

# ---------------------------------------------------------------------------
# Severity ordering for threshold comparison
# ---------------------------------------------------------------------------
_SEVERITY_RANK: Dict[str, int] = {
    "LOW": 1,
    "MEDIUM": 2,
    "HIGH": 3,
    "CRITICAL": 4,
}


def _severity_meets_threshold(severity: str, threshold: str) -> bool:
    """Check if a severity level meets or exceeds the threshold.

    Args:
        severity:  Playbook severity string (e.g. "CRITICAL").
        threshold: Minimum severity to trigger alert (e.g. "HIGH").

    Returns:
        True if severity >= threshold in the ranking.
    """
    sev_rank = _SEVERITY_RANK.get(severity.upper(), 0)
    thr_rank = _SEVERITY_RANK.get(threshold.upper(), 4)
    return sev_rank >= thr_rank


# ---------------------------------------------------------------------------
# HTML Email Template
# ---------------------------------------------------------------------------

_EMAIL_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PhantomNet Sentinel Alert</title>
</head>
<body style="margin:0; padding:0; font-family:'Segoe UI',Roboto,Arial,sans-serif; background-color:#0f172a;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0f172a; padding:32px 0;">
    <tr>
      <td align="center">
        <table width="640" cellpadding="0" cellspacing="0" style="background-color:#1e293b; border-radius:12px; overflow:hidden; box-shadow:0 4px 24px rgba(0,0,0,0.4);">

          <!-- Header Banner -->
          <tr>
            <td style="background:linear-gradient(135deg,#dc2626 0%,#991b1b 100%); padding:28px 32px; text-align:center;">
              <h1 style="margin:0; color:#ffffff; font-size:22px; font-weight:700; letter-spacing:0.5px;">
                &#9888;&#65039; SENTINEL ALERT — {severity} SEVERITY
              </h1>
              <p style="margin:8px 0 0; color:#fecaca; font-size:13px;">
                PhantomNet Threat Intelligence • Automated Playbook Generated
              </p>
            </td>
          </tr>

          <!-- Playbook Details -->
          <tr>
            <td style="padding:28px 32px;">
              <h2 style="margin:0 0 16px; color:#f8fafc; font-size:18px; font-weight:600;">
                {playbook_name}
              </h2>

              <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:20px;">
                <tr>
                  <td style="padding:10px 14px; background-color:#0f172a; border-radius:8px 8px 0 0; border-bottom:1px solid #334155;">
                    <span style="color:#94a3b8; font-size:12px; text-transform:uppercase; letter-spacing:1px;">Playbook ID</span><br>
                    <span style="color:#e2e8f0; font-size:15px; font-weight:500;">{playbook_id}</span>
                  </td>
                </tr>
                <tr>
                  <td style="padding:10px 14px; background-color:#0f172a; border-bottom:1px solid #334155;">
                    <span style="color:#94a3b8; font-size:12px; text-transform:uppercase; letter-spacing:1px;">Severity</span><br>
                    <span style="color:{severity_color}; font-size:15px; font-weight:700;">{severity}</span>
                  </td>
                </tr>
                <tr>
                  <td style="padding:10px 14px; background-color:#0f172a; border-bottom:1px solid #334155;">
                    <span style="color:#94a3b8; font-size:12px; text-transform:uppercase; letter-spacing:1px;">Attack Type</span><br>
                    <span style="color:#e2e8f0; font-size:15px; font-weight:500;">{attack_type}</span>
                  </td>
                </tr>
                <tr>
                  <td style="padding:10px 14px; background-color:#0f172a; border-bottom:1px solid #334155;">
                    <span style="color:#94a3b8; font-size:12px; text-transform:uppercase; letter-spacing:1px;">MITRE ATT&CK</span><br>
                    <span style="color:#e2e8f0; font-size:15px; font-weight:500;">{technique_id} — {technique_name}</span>
                  </td>
                </tr>
                <tr>
                  <td style="padding:10px 14px; background-color:#0f172a; border-bottom:1px solid #334155;">
                    <span style="color:#94a3b8; font-size:12px; text-transform:uppercase; letter-spacing:1px;">Threat Score</span><br>
                    <span style="color:#fbbf24; font-size:15px; font-weight:700;">{threat_score}</span>
                  </td>
                </tr>
                <tr>
                  <td style="padding:10px 14px; background-color:#0f172a; border-bottom:1px solid #334155;">
                    <span style="color:#94a3b8; font-size:12px; text-transform:uppercase; letter-spacing:1px;">Source IP</span><br>
                    <span style="color:#e2e8f0; font-size:15px; font-weight:500;">{src_ip}</span>
                  </td>
                </tr>
                <tr>
                  <td style="padding:10px 14px; background-color:#0f172a; border-radius:0 0 8px 8px;">
                    <span style="color:#94a3b8; font-size:12px; text-transform:uppercase; letter-spacing:1px;">Generated At</span><br>
                    <span style="color:#e2e8f0; font-size:15px; font-weight:500;">{generated_at}</span>
                  </td>
                </tr>
              </table>

              <!-- Summary Section -->
              <div style="padding:16px; background-color:#0f172a; border-radius:8px; border-left:4px solid #dc2626; margin-bottom:24px;">
                <h3 style="margin:0 0 8px; color:#f8fafc; font-size:14px; font-weight:600;">Summary</h3>
                <p style="margin:0; color:#cbd5e1; font-size:14px; line-height:1.6;">
                  {summary}
                </p>
              </div>

              <!-- Dashboard Link -->
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td align="center" style="padding:8px 0;">
                    <a href="{dashboard_url}" target="_blank"
                       style="display:inline-block; padding:14px 36px; background:linear-gradient(135deg,#2563eb 0%,#1d4ed8 100%); color:#ffffff; font-size:15px; font-weight:600; text-decoration:none; border-radius:8px; letter-spacing:0.3px;">
                      View Playbook in Dashboard &rarr;
                    </a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:20px 32px; background-color:#0f172a; border-top:1px solid #1e293b; text-align:center;">
              <p style="margin:0; color:#475569; font-size:12px;">
                This is an automated alert from PhantomNet Sentinel Layer.<br>
                Do not reply to this email. Configure alerts via SENTINEL_EMAIL_* environment variables.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
"""

_EMAIL_PLAIN_TEMPLATE = """\
============================================================
  PHANTOMNET SENTINEL ALERT — {severity} SEVERITY
============================================================

Playbook: {playbook_name}
Playbook ID: {playbook_id}
Severity: {severity}
Attack Type: {attack_type}
MITRE ATT&CK: {technique_id} — {technique_name}
Threat Score: {threat_score}
Source IP: {src_ip}
Generated At: {generated_at}

SUMMARY
-------
{summary}

VIEW IN DASHBOARD:
{dashboard_url}

------------------------------------------------------------
This is an automated alert from PhantomNet Sentinel Layer.
Do not reply to this email.
"""

# Severity → color mapping for HTML template
_SEVERITY_COLORS: Dict[str, str] = {
    "CRITICAL": "#ef4444",
    "HIGH": "#f97316",
    "MEDIUM": "#eab308",
    "LOW": "#22c55e",
}


# ---------------------------------------------------------------------------
# Email Alert Dispatcher
# ---------------------------------------------------------------------------

class SentinelEmailNotifier:
    """Dispatches email alerts for high-severity sentinel playbooks.

    Reads SMTP configuration from sentinel_config at instantiation time.
    All email sending is performed asynchronously to avoid blocking the
    main Sentinel pipeline.

    Attributes
    ----------
    enabled : bool
        Whether email alerts are enabled.
    smtp_host : str
        SMTP server hostname.
    smtp_port : int
        SMTP server port.
    smtp_user : str
        SMTP authentication username.
    smtp_password : str
        SMTP authentication password.
    use_tls : bool
        Whether to use STARTTLS.
    from_address : str
        Sender email address.
    recipients : list[str]
        List of recipient email addresses.
    severity_threshold : str
        Minimum severity to trigger alerts.
    dashboard_base_url : str
        Base URL for constructing dashboard deep links.
    """

    def __init__(self) -> None:
        """Initialize the email notifier with configuration from environment."""
        from config.sentinel_config import (
            SENTINEL_EMAIL_ALERTS_ENABLED,
            SENTINEL_EMAIL_SMTP_HOST,
            SENTINEL_EMAIL_SMTP_PORT,
            SENTINEL_EMAIL_SMTP_USER,
            SENTINEL_EMAIL_SMTP_PASSWORD,
            SENTINEL_EMAIL_SMTP_USE_TLS,
            SENTINEL_EMAIL_FROM_ADDRESS,
            SENTINEL_EMAIL_RECIPIENTS,
            SENTINEL_EMAIL_SEVERITY_THRESHOLD,
            SENTINEL_DASHBOARD_BASE_URL,
        )

        self.enabled = SENTINEL_EMAIL_ALERTS_ENABLED
        self.smtp_host = SENTINEL_EMAIL_SMTP_HOST
        self.smtp_port = SENTINEL_EMAIL_SMTP_PORT
        self.smtp_user = SENTINEL_EMAIL_SMTP_USER
        self.smtp_password = SENTINEL_EMAIL_SMTP_PASSWORD
        self.use_tls = SENTINEL_EMAIL_SMTP_USE_TLS
        self.recipients = list(SENTINEL_EMAIL_RECIPIENTS)
        self.severity_threshold = SENTINEL_EMAIL_SEVERITY_THRESHOLD
        self.dashboard_base_url = SENTINEL_DASHBOARD_BASE_URL

        try:
            from services.system_config_service import get_config_str
            cfg_email = get_config_str("alert_email", "")
            if cfg_email and cfg_email not in self.recipients:
                self.recipients.append(cfg_email)
            cfg_sev = get_config_str("alert_severity_filter", "")
            if cfg_sev:
                self.severity_threshold = cfg_sev.upper()
        except Exception:
            pass

        if self.enabled:
            logger.info(
                "SentinelEmailNotifier initialized: smtp=%s:%d, "
                "from=%s, recipients=%d, threshold=%s",
                self.smtp_host, self.smtp_port,
                self.from_address, len(self.recipients),
                self.severity_threshold,
            )
        else:
            logger.debug("SentinelEmailNotifier disabled (SENTINEL_EMAIL_ALERTS_ENABLED=false)")

    def should_alert(self, severity: Optional[str]) -> bool:
        """Determine whether an alert should be sent for the given severity.

        Args:
            severity: Playbook severity string (e.g. "CRITICAL", "HIGH").

        Returns:
            True if alerts are enabled and severity meets the threshold.
        """
        if not self.enabled:
            return False
        if not severity:
            return False
        if not self.recipients:
            logger.warning("Email alerts enabled but no recipients configured")
            return False
        return _severity_meets_threshold(severity, self.severity_threshold)

    def build_email_context(self, playbook) -> Dict[str, str]:
        """Extract template context variables from a SentinelPlaybook record.

        Args:
            playbook: SentinelPlaybook ORM object.

        Returns:
            Dictionary of template variables for email rendering.
        """
        severity = (playbook.severity or "UNKNOWN").upper()
        playbook_db_id = getattr(playbook, "id", "")
        dashboard_url = (
            f"{self.dashboard_base_url}/sentinel/playbooks/{playbook_db_id}"
            if self.dashboard_base_url
            else "#"
        )

        # Build summary from available data
        summary_parts = []
        if playbook.attack_type:
            summary_parts.append(
                f"Detected {playbook.attack_type} attack pattern"
            )
        if playbook.src_ip:
            summary_parts.append(f"from source IP {playbook.src_ip}")
        if playbook.dst_port:
            summary_parts.append(f"targeting port {playbook.dst_port}")
        if playbook.tactic:
            summary_parts.append(
                f"mapped to MITRE ATT&CK tactic '{playbook.tactic}'"
            )
        if playbook.threat_score is not None:
            summary_parts.append(
                f"with threat score {playbook.threat_score:.1f}"
            )
        summary = " ".join(summary_parts) + "." if summary_parts else (
            "A high-severity playbook has been automatically generated "
            "and requires analyst review."
        )

        generated_at = ""
        if playbook.created_at:
            if isinstance(playbook.created_at, datetime):
                generated_at = playbook.created_at.strftime("%Y-%m-%d %H:%M:%S UTC")
            else:
                generated_at = str(playbook.created_at)

        return {
            "playbook_name": playbook.playbook_name or "Sentinel Playbook",
            "playbook_id": playbook.playbook_id or "N/A",
            "severity": severity,
            "severity_color": _SEVERITY_COLORS.get(severity, "#94a3b8"),
            "attack_type": playbook.attack_type or "Unknown",
            "technique_id": playbook.technique_id or "N/A",
            "technique_name": playbook.technique_name or "N/A",
            "threat_score": f"{playbook.threat_score:.1f}" if playbook.threat_score is not None else "N/A",
            "src_ip": playbook.src_ip or "N/A",
            "generated_at": generated_at,
            "summary": summary,
            "dashboard_url": dashboard_url,
        }

    def compose_email(self, context: Dict[str, str]) -> MIMEMultipart:
        """Compose a MIME multipart email from the template context.

        Args:
            context: Template variable dictionary from build_email_context().

        Returns:
            MIMEMultipart email message ready to send.
        """
        msg = MIMEMultipart("alternative")
        msg["Subject"] = (
            f"[PhantomNet Sentinel] {context['severity']} ALERT — "
            f"{context['playbook_name']}"
        )
        msg["From"] = self.from_address
        msg["To"] = ", ".join(self.recipients)
        msg["X-Priority"] = "1" if context["severity"] == "CRITICAL" else "2"
        msg["X-PhantomNet-Playbook-ID"] = context["playbook_id"]
        msg["X-PhantomNet-Severity"] = context["severity"]

        # Plain text version
        plain_body = _EMAIL_PLAIN_TEMPLATE.format(**context)
        msg.attach(MIMEText(plain_body, "plain", "utf-8"))

        # HTML version
        html_body = _EMAIL_HTML_TEMPLATE.format(**context)
        msg.attach(MIMEText(html_body, "html", "utf-8"))

        return msg

    def _send_smtp(self, msg: MIMEMultipart) -> bool:
        """Send an email via SMTP (blocking call).

        Args:
            msg: Composed MIMEMultipart email message.

        Returns:
            True if email was sent successfully, False otherwise.
        """
        try:
            if self.use_tls:
                server = smtplib.SMTP(self.smtp_host, self.smtp_port, timeout=30)
                server.ehlo()
                server.starttls()
                server.ehlo()
            else:
                server = smtplib.SMTP(self.smtp_host, self.smtp_port, timeout=30)
                server.ehlo()

            if self.smtp_user and self.smtp_password:
                server.login(self.smtp_user, self.smtp_password)

            server.sendmail(
                self.from_address,
                self.recipients,
                msg.as_string(),
            )
            server.quit()
            logger.info(
                "Email alert sent successfully to %d recipient(s): %s",
                len(self.recipients),
                msg["Subject"],
            )
            return True

        except smtplib.SMTPAuthenticationError as exc:
            logger.error(
                "SMTP authentication failed for %s@%s:%d — %s",
                self.smtp_user, self.smtp_host, self.smtp_port, exc,
            )
            return False
        except smtplib.SMTPConnectError as exc:
            logger.error(
                "Failed to connect to SMTP server %s:%d — %s",
                self.smtp_host, self.smtp_port, exc,
            )
            return False
        except smtplib.SMTPException as exc:
            logger.error("SMTP error sending alert email: %s", exc)
            return False
        except Exception as exc:
            logger.error(
                "Unexpected error sending alert email: %s", exc, exc_info=True,
            )
            return False

    def send_alert(self, playbook) -> bool:
        """Send an alert email for a playbook (blocking).

        Checks severity threshold, composes the email, and sends via SMTP.

        Args:
            playbook: SentinelPlaybook ORM object.

        Returns:
            True if the email was sent, False if skipped or failed.
        """
        severity = getattr(playbook, "severity", None)
        if not self.should_alert(severity):
            logger.debug(
                "Email alert skipped for playbook %s (severity=%s, threshold=%s)",
                getattr(playbook, "playbook_id", "?"),
                severity,
                self.severity_threshold,
            )
            return False

        context = self.build_email_context(playbook)
        msg = self.compose_email(context)
        return self._send_smtp(msg)

    def send_alert_async(self, playbook) -> None:
        """Send an alert email asynchronously in a background thread.

        This is the primary entry point called by the Sentinel pipeline.
        The email is sent in a daemon thread to avoid blocking playbook
        generation.

        Args:
            playbook: SentinelPlaybook ORM object. Must have all fields
                populated before calling (since the background thread
                cannot access the DB session).
        """
        severity = getattr(playbook, "severity", None)
        if not self.should_alert(severity):
            return

        # Snapshot all needed attributes before dispatching to background
        # thread (the ORM object may be detached from its session later).
        context = self.build_email_context(playbook)
        playbook_id_str = getattr(playbook, "playbook_id", "?")

        def _dispatch():
            try:
                msg = self.compose_email(context)
                success = self._send_smtp(msg)
                if success:
                    logger.info(
                        "Async email alert dispatched for playbook %s",
                        playbook_id_str,
                    )
                else:
                    logger.warning(
                        "Async email alert failed for playbook %s",
                        playbook_id_str,
                    )
            except Exception as exc:
                logger.error(
                    "Async email alert error for playbook %s: %s",
                    playbook_id_str, exc,
                )

        thread = threading.Thread(target=_dispatch, daemon=True)
        thread.start()
        logger.info(
            "Email alert thread started for playbook %s (severity=%s)",
            playbook_id_str, severity,
        )


# ---------------------------------------------------------------------------
# Module-level singleton (lazy-initialized)
# ---------------------------------------------------------------------------
_notifier_instance: Optional[SentinelEmailNotifier] = None
_notifier_lock = threading.Lock()


def get_email_notifier() -> SentinelEmailNotifier:
    """Return the module-level SentinelEmailNotifier singleton.

    Thread-safe lazy initialization ensures the notifier is created
    only once and reuses SMTP configuration across all pipeline calls.

    Returns:
        SentinelEmailNotifier instance.
    """
    global _notifier_instance
    if _notifier_instance is None:
        with _notifier_lock:
            if _notifier_instance is None:
                _notifier_instance = SentinelEmailNotifier()
    return _notifier_instance


def trigger_email_alert_async(playbook) -> None:
    """Convenience function: trigger an async email alert for a playbook.

    Called from SentinelService.generate_playbook() after successful
    DB persistence. Only sends if severity meets the configured threshold.

    Args:
        playbook: SentinelPlaybook ORM object with all fields populated.
    """
    try:
        notifier = get_email_notifier()
        notifier.send_alert_async(playbook)
    except Exception as exc:
        logger.warning(
            "Failed to trigger email alert for playbook %s: %s",
            getattr(playbook, "playbook_id", "?"), exc,
        )
