"""
backend/sentinel/models.py
---------------------------
PhantomNet Sentinel Layer ΓÇö Database Models

Defines the SentinelPlaybook ORM model, which stores one playbook record
per detected threat event.  Records are created by sentinel_service.py
(Phase 5, Day 5) and surfaced by the Sentinel Dashboard REST API
(api/sentinel.py, Phase 5, Day 6+).

Table auto-creation
-------------------
Import this module BEFORE ``Base.metadata.create_all()`` is called in
``backend/main.py`` so SQLAlchemy sees the model and creates the table.
This is already wired in main.py under the Sentinel Models section.

SentinelPlaybook Schema (27 columns)
-------------------------------------
  Core Identity (4)
    id, created_at, updated_at, playbook_id

  Version Tracking (4)
    version, parent_id, is_latest, regeneration_reason

  Threat Context (7)
    src_ip, dst_port, protocol, attack_type, threat_score,
    confidence_score, severity

  MITRE ATT&CK Mapping (4)
    technique_id, technique_name, tactic, mitre_url

  Snort Rule (2)
    snort_rule, sigma_rule

  Playbook Content (3)
    playbook_name, playbook_content, template_name

  Lifecycle (3)
    status, reviewed_by, reviewed_at

Usage
-----
    from sentinel.models import SentinelPlaybook
    from database.database import SessionLocal

    db = SessionLocal()
    playbook = db.query(SentinelPlaybook).filter_by(status="pending").all()
"""

from __future__ import annotations

from datetime import datetime
import logging
from typing import Any, Dict, List, Optional, Union

logger = logging.getLogger("sentinel.models")

from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

# Import the shared declarative Base so this model is registered in the same
# metadata as all other PhantomNet ORM models.  This is required for
# Base.metadata.create_all(bind=engine) in main.py to discover and create the
# sentinel_playbooks table automatically on startup.
from database.models import Base


class SentinelPlaybook(Base):
    """
    ORM model for the ``sentinel_playbooks`` table.

    One row is created per detected threat event that passes through the
    Sentinel pipeline.  The pipeline flow is:

        PacketLog (detected_signatures)
            ΓåÆ mitre_mapper.map_signature()    ΓåÆ technique_id / technique_name / tactic / mitre_url
            ΓåÆ rule_generator.generate_snort_rule() ΓåÆ snort_rule
            ΓåÆ playbook_generator.render()     ΓåÆ playbook_name / playbook_content / template_name
            ΓåÆ SentinelPlaybook (this table)

    The Sentinel Dashboard reads rows from this table and allows analysts to
    approve, reject, and export playbooks.
    """

    __tablename__ = "sentinel_playbooks"
    __table_args__ = {"extend_existing": True}

    # ΓöÇΓöÇ 1. Core Identity ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   id          : Auto-increment primary key.
    #   playbook_id : Human-readable unique identifier, e.g. "PB-20260617-0001".
    #                 Generated by sentinel_service.py before INSERT.
    #   created_at  : Row creation timestamp (UTC).
    #   updated_at  : Last modification timestamp; auto-updated on every write.

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    playbook_id = Column(
        String(64),
        unique=True,
        nullable=False,
        index=True,
        comment="Human-readable unique identifier, e.g. PB-20260617-0001",
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True,
        comment="UTC timestamp when the playbook record was created",
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
        comment="UTC timestamp of last modification; auto-updated on save",
    )

    # ── 1b. Version Tracking ─────────────────────────────────────────────
    #   version              : Monotonically increasing revision number (1-based).
    #   parent_id            : FK to the previous version's row (NULL for v1).
    #   is_latest            : True only for the most current revision of a
    #                          playbook lineage. Dashboard queries filter on
    #                          this to avoid showing superseded versions.
    #   regeneration_reason  : Human-readable reason for regeneration (audit).

    version = Column(
        Integer,
        nullable=False,
        default=1,
        comment="Revision number for this playbook (1 = original, 2+ = regenerated)",
    )

    parent_id = Column(
        Integer,
        ForeignKey("sentinel_playbooks.id", ondelete="SET NULL"),
        nullable=True,
        default=None,
        index=True,
        comment="FK to the previous version's row ID (NULL for first version)",
    )

    is_latest = Column(
        Boolean,
        nullable=False,
        default=True,
        index=True,
        comment="True if this is the most recent version of the playbook lineage",
    )

    regeneration_reason = Column(
        String(512),
        nullable=True,
        default=None,
        comment="Reason for regeneration, e.g. 'Updated threat intelligence' or 'Analyst-requested refresh'",
    )

    # Self-referential relationship for version chain navigation
    parent = relationship(
        "SentinelPlaybook",
        remote_side=[id],
        backref="child_versions",
        foreign_keys=[parent_id],
    )

    # ΓöÇΓöÇ 2. Threat Context ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   src_ip      : Attacker source IP captured in PacketLog.
    #   dst_port    : Destination port that determined honeypot service type.
    #   protocol    : Network protocol (TCP, UDP, ICMP, IP).
    #   attack_type : ML classification label (e.g. SSH_AUTH_FAILURE).
    #   threat_score: ML confidence score 0.0ΓÇô100.0.

    src_ip = Column(
        String(45),
        nullable=True,
        index=True,
        comment="Attacker source IP address (IPv4 or IPv6)",
    )

    dst_port = Column(
        Integer,
        nullable=True,
        index=True,
        comment="Destination port used to infer honeypot service type",
    )

    protocol = Column(
        String(16),
        nullable=True,
        comment="Network protocol: TCP | UDP | ICMP | IP",
    )

    attack_type = Column(
        String(128),
        nullable=True,
        index=True,
        comment="ML attack classification label, e.g. SSH_AUTH_FAILURE",
    )

    threat_score = Column(
        Float,
        nullable=True,
        default=0.0,
        comment="ML threat confidence score in range 0.0ΓÇô100.0",
    )

    confidence_score = Column(
        Float,
        nullable=True,
        default=None,
        comment=(
            "Composite playbook confidence score in range 0.0–1.0. "
            "Computed from cluster_size_score, ml_avg_score, ioc_density, "
            "and multi_proto_bonus via weighted average in confidence_scoring.py."
        ),
    )

    quality_score = Column(
        Float,
        nullable=True,
        default=0.0,
        comment="Dynamic quality score (0-100) based on IOC count, cluster volume, model confidence, and multi-source verification.",
    )

    severity = Column(
        String(16),
        nullable=True,
        default=None,
        index=True,
        comment=(
            "Severity tier derived from confidence_score: "
            "CRITICAL (>=0.8) | HIGH (>=0.6) | MEDIUM (>=0.4) | LOW (<0.4)"
        ),
    )

    # ── 3. MITRE ATT&CK Mapping ──────────────────────────────────────────────
    #   technique_id   : e.g. "T1110.001"
    #   technique_name : e.g. "Brute Force: Password Guessing"
    #   tactic         : e.g. "Credential Access"
    #   mitre_url      : Official ATT&CK reference URL

    technique_id = Column(
        String(32),
        nullable=True,
        index=True,
        comment="MITRE ATT&CK technique ID, e.g. T1110.001",
    )

    technique_name = Column(
        String(256),
        nullable=True,
        comment="MITRE ATT&CK technique name, e.g. Brute Force: Password Guessing",
    )

    tactic = Column(
        String(128),
        nullable=True,
        comment="MITRE ATT&CK tactic name, e.g. Credential Access",
    )

    mitre_url = Column(
        String(512),
        nullable=True,
        comment="Official MITRE ATT&CK technique reference URL",
    )

    # ΓöÇΓöÇ 4. Detection Rules ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   snort_rule : Generated Snort IDS rule string (may be multi-line).
    #   sigma_rule : Generated Sigma detection rule in YAML format (reserved
    #                for Phase 6; nullable until rule_generator supports Sigma).

    snort_rule = Column(
        Text,
        nullable=True,
        comment="Generated Snort IDS rule string produced by rule_generator.py",
    )

    sigma_rule = Column(
        Text,
        nullable=True,
        comment="Generated Sigma YAML rule (reserved for Phase 6; currently null)",
    )

    # ΓöÇΓöÇ 5. Playbook Content ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   playbook_name    : Short descriptive name, e.g. "SSH Brute Force Response".
    #   playbook_content : Full rendered Jinja2 playbook Markdown/text body.
    #   template_name    : Name of the Jinja2 template used, e.g. "ssh_brute_force.j2".

    playbook_name = Column(
        String(256),
        nullable=True,
        comment="Short human-readable playbook title",
    )

    playbook_content = Column(
        Text,
        nullable=True,
        comment="Full rendered playbook body (Markdown format)",
    )

    template_name = Column(
        String(128),
        nullable=True,
        comment="Jinja2 template filename used to render playbook_content",
    )

    llm_narrative = Column(
        Text,
        nullable=True,
        default=None,
        comment="AI-generated playbook narrative summary (Markdown format)",
    )

    # ΓöÇΓöÇ 6. Lifecycle / Workflow ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   status      : Approval workflow state.
    #                 Values: "pending" | "approved" | "rejected" | "exported"
    #                 Default is "pending" ΓÇö all new playbooks await analyst review.
    #   reviewed_by : Username of the analyst who approved/rejected the playbook.
    #   reviewed_at : UTC timestamp of the approval/rejection action.

    status = Column(
        String(32),
        nullable=False,
        default="pending",
        index=True,
        comment="Workflow status: pending | approved | rejected | exported",
    )

    reviewed_by = Column(
        String(128),
        nullable=True,
        comment="Username of the analyst who approved or rejected this playbook",
    )

    reviewed_at = Column(
        DateTime,
        nullable=True,
        comment="UTC timestamp when the analyst reviewed this playbook",
    )

    # ΓöÇΓöÇ Helpers ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

    # ── Helpers ────────────────────────────────────────────────────────────

    def __repr__(self) -> str:  # pragma: no cover
        """Return a developer-friendly string representation of the playbook record."""
        return (
            f"<SentinelPlaybook id={self.id} playbook_id={self.playbook_id!r} "
            f"v{self.version} attack_type={self.attack_type!r} "
            f"confidence={self.confidence_score} severity={self.severity!r} "
            f"status={self.status!r} is_latest={self.is_latest}>"
        )

    def to_dict(self) -> Dict[str, Any]:
        """
        Serialize all 27 columns to a plain dictionary.

        Used by the REST API (api/sentinel.py) to build JSON responses without
        importing Pydantic schemas in the model layer.

        Returns:
            dict: All column values with ISO-8601 timestamps for datetime fields.
        """
        return {
            # Core Identity
            "id":               self.id,
            "playbook_id":      self.playbook_id,
            "created_at":       self.created_at.isoformat() if self.created_at else None,
            "updated_at":       self.updated_at.isoformat() if self.updated_at else None,
            # Version Tracking
            "version":              self.version,
            "parent_id":            self.parent_id,
            "is_latest":            self.is_latest,
            "regeneration_reason":  self.regeneration_reason,
            # Threat Context
            "src_ip":           self.src_ip,
            "dst_port":         self.dst_port,
            "protocol":         self.protocol,
            "attack_type":      self.attack_type,
            "threat_score":     self.threat_score,
            "confidence_score": self.confidence_score,
            "quality_score":    self.quality_score,
            "severity":         self.severity,
            # MITRE ATT&CK
            "technique_id":     self.technique_id,
            "technique_name":   self.technique_name,
            "tactic":           self.tactic,
            "mitre_url":        self.mitre_url,
            # Detection Rules
            "snort_rule":       self.snort_rule,
            "sigma_rule":       self.sigma_rule,
            # Playbook Content
            "playbook_name":    self.playbook_name,
            "playbook_content": self.playbook_content,
            "template_name":    self.template_name,
            "llm_narrative":    self.llm_narrative,
            # Lifecycle
            "status":           self.status,
            "reviewed_by":      self.reviewed_by,
            "reviewed_at":      self.reviewed_at.isoformat() if self.reviewed_at else None,
        }

    # ── Version History Queries ────────────────────────────────────────────

    @classmethod
    def get_version_history(
        cls,
        db,
        playbook_id: Optional[str] = None,
        parent_chain_id: Optional[int] = None,
    ) -> List["SentinelPlaybook"]:
        """Retrieve the full version history for a playbook lineage.

        Walks the ``parent_id`` chain to collect all versions of a playbook,
        ordered from newest to oldest.

        Args:
            db: Active SQLAlchemy session.
            playbook_id: Human-readable playbook_id of *any* version in the
                chain.  The method resolves the root and retrieves all
                descendants.
            parent_chain_id: Database ``id`` of any row in the chain.  Used
                as an alternative to *playbook_id* when the caller has the
                integer PK.

        Returns:
            List of SentinelPlaybook rows ordered by ``version`` descending
            (newest first).
        """
        if playbook_id is None and parent_chain_id is None:
            raise ValueError("Provide either playbook_id or parent_chain_id")

        # Find the starting row
        if playbook_id is not None:
            start = db.query(cls).filter(cls.playbook_id == playbook_id).first()
        else:
            start = db.query(cls).filter(cls.id == parent_chain_id).first()

        if start is None:
            return []

        # Walk UP to the root (v1)
        root = start
        while root.parent_id is not None:
            parent_row = db.query(cls).filter(cls.id == root.parent_id).first()
            if parent_row is None:
                break
            root = parent_row

        # Collect ALL versions via recursive descent from root
        collected = [root]
        queue = [root.id]
        while queue:
            current_id = queue.pop(0)
            children = (
                db.query(cls)
                .filter(cls.parent_id == current_id)
                .order_by(cls.version.asc())
                .all()
            )
            for child in children:
                collected.append(child)
                queue.append(child.id)

        # Sort newest first
        collected.sort(key=lambda r: r.version, reverse=True)
        return collected

    @classmethod
    def get_latest_version(
        cls,
        db,
        parent_chain_id: int,
    ) -> Optional["SentinelPlaybook"]:
        """Return the latest version of a playbook by walking from any row.

        Args:
            db: Active SQLAlchemy session.
            parent_chain_id: Database ``id`` of any row in the version chain.

        Returns:
            The SentinelPlaybook row with ``is_latest=True`` in the chain,
            or None if not found.
        """
        # First, try the fast path: walk up to root, then find is_latest=True
        start = db.query(cls).filter(cls.id == parent_chain_id).first()
        if start is None:
            return None

        # Walk up to root
        root = start
        while root.parent_id is not None:
            parent_row = db.query(cls).filter(cls.id == root.parent_id).first()
            if parent_row is None:
                break
            root = parent_row

        # From root, find the one with is_latest=True
        history = cls.get_version_history(db, parent_chain_id=root.id)
        for row in history:
            if row.is_latest:
                return row

        # Fallback: return the highest version
        return history[0] if history else None


class SentinelAuditLog(Base):
    """
    ORM model for recording analyst and system audit events on Sentinel playbooks.

    Tracks actions such as approve, reject, regenerate, export, batch operations,
    and retention purges.
    """

    __tablename__ = "sentinel_audit_logs"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    playbook_id = Column(String(64), nullable=True, index=True, comment="Associated playbook ID or NULL for system actions")
    action = Column(String(64), nullable=False, index=True, comment="Audit action: approve | reject | regenerate | export | batch_approve | archive")
    user = Column(String(128), nullable=False, default="system", comment="Username or service performing the action")
    details = Column(Text, nullable=True, comment="JSON string or free text providing action metadata")
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True, comment="UTC timestamp of the audit event")

    def to_dict(self) -> Dict[str, Any]:
        """Serialize audit log record to dictionary."""
        return {
            "id": self.id,
            "playbook_id": self.playbook_id,
            "action": self.action,
            "user": self.user,
            "details": self.details,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
        }

    @classmethod
    def log_event(
        cls,
        db,
        action: str,
        user: str = "system",
        playbook_id: Optional[str] = None,
        details: Optional[Union[Dict[str, Any], str]] = None,
        commit: bool = False,
    ) -> "SentinelAuditLog":
        """
        Record an audit log entry using audit_logger module.

        Args:
            db: Active SQLAlchemy database session.
            action: Audit action name (approve, reject, export, regenerate, etc.).
            user: Username or service performing the action.
            playbook_id: Optional target playbook ID.
            details: Event metadata dictionary or string.
            commit: Whether to commit immediately.

        Returns:
            Created SentinelAuditLog instance.
        """
        from sentinel.audit_logger import log_audit_event
        return log_audit_event(
            db=db,
            action=action,
            user=user,
            playbook_id=playbook_id,
            details=details,
            commit=commit,
        )


