"""
backend/sentinel/models.py
---------------------------
PhantomNet Sentinel Layer ΓÇö Database Models

Defines the SentinelPlaybook ORM model, which stores one playbook record
per detected threat event.  Records are created by sentinel_service.py
(Phase 5, Day 5) and surfaced by the Sentinel Dashboard REST API
(api/sentinel.py, Phase 5, Day 6+).

Table auto-creation
-------------------
Import this module BEFORE ``Base.metadata.create_all()`` is called in
``backend/main.py`` so SQLAlchemy sees the model and creates the table.
This is already wired in main.py under the Sentinel Models section.

SentinelPlaybook Schema (23 columns)
-------------------------------------
  Core Identity (4)
    id, created_at, updated_at, playbook_id

  Threat Context (7)
    src_ip, dst_port, protocol, attack_type, threat_score,
    confidence_score, severity

  MITRE ATT&CK Mapping (4)
    technique_id, technique_name, tactic, mitre_url

  Snort Rule (2)
    snort_rule, sigma_rule

  Playbook Content (3)
    playbook_name, playbook_content, template_name

  Lifecycle (3)
    status, reviewed_by, reviewed_at

Usage
-----
    from sentinel.models import SentinelPlaybook
    from database.database import SessionLocal

    db = SessionLocal()
    playbook = db.query(SentinelPlaybook).filter_by(status="pending").all()
"""

from __future__ import annotations

from datetime import datetime
import logging
from typing import Any, Dict, Optional

logger = logging.getLogger("sentinel.models")

from sqlalchemy import Boolean, Column, DateTime, Float, Integer, String, Text

# Import the shared declarative Base so this model is registered in the same
# metadata as all other PhantomNet ORM models.  This is required for
# Base.metadata.create_all(bind=engine) in main.py to discover and create the
# sentinel_playbooks table automatically on startup.
from database.models import Base


class SentinelPlaybook(Base):
    """
    ORM model for the ``sentinel_playbooks`` table.

    One row is created per detected threat event that passes through the
    Sentinel pipeline.  The pipeline flow is:

        PacketLog (detected_signatures)
            ΓåÆ mitre_mapper.map_signature()    ΓåÆ technique_id / technique_name / tactic / mitre_url
            ΓåÆ rule_generator.generate_snort_rule() ΓåÆ snort_rule
            ΓåÆ playbook_generator.render()     ΓåÆ playbook_name / playbook_content / template_name
            ΓåÆ SentinelPlaybook (this table)

    The Sentinel Dashboard reads rows from this table and allows analysts to
    approve, reject, and export playbooks.
    """

    __tablename__ = "sentinel_playbooks"
    __table_args__ = {"extend_existing": True}

    # ΓöÇΓöÇ 1. Core Identity ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   id          : Auto-increment primary key.
    #   playbook_id : Human-readable unique identifier, e.g. "PB-20260617-0001".
    #                 Generated by sentinel_service.py before INSERT.
    #   created_at  : Row creation timestamp (UTC).
    #   updated_at  : Last modification timestamp; auto-updated on every write.

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    playbook_id = Column(
        String(64),
        unique=True,
        nullable=False,
        index=True,
        comment="Human-readable unique identifier, e.g. PB-20260617-0001",
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True,
        comment="UTC timestamp when the playbook record was created",
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
        comment="UTC timestamp of last modification; auto-updated on save",
    )

    # ΓöÇΓöÇ 2. Threat Context ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   src_ip      : Attacker source IP captured in PacketLog.
    #   dst_port    : Destination port that determined honeypot service type.
    #   protocol    : Network protocol (TCP, UDP, ICMP, IP).
    #   attack_type : ML classification label (e.g. SSH_AUTH_FAILURE).
    #   threat_score: ML confidence score 0.0ΓÇô100.0.

    src_ip = Column(
        String(45),
        nullable=True,
        index=True,
        comment="Attacker source IP address (IPv4 or IPv6)",
    )

    dst_port = Column(
        Integer,
        nullable=True,
        index=True,
        comment="Destination port used to infer honeypot service type",
    )

    protocol = Column(
        String(16),
        nullable=True,
        comment="Network protocol: TCP | UDP | ICMP | IP",
    )

    attack_type = Column(
        String(128),
        nullable=True,
        index=True,
        comment="ML attack classification label, e.g. SSH_AUTH_FAILURE",
    )

    threat_score = Column(
        Float,
        nullable=True,
        default=0.0,
        comment="ML threat confidence score in range 0.0ΓÇô100.0",
    )

    confidence_score = Column(
        Float,
        nullable=True,
        default=None,
        comment=(
            "Composite playbook confidence score in range 0.0–1.0. "
            "Computed from cluster_size_score, ml_avg_score, ioc_density, "
            "and multi_proto_bonus via weighted average in confidence_scoring.py."
        ),
    )

    severity = Column(
        String(16),
        nullable=True,
        default=None,
        index=True,
        comment=(
            "Severity tier derived from confidence_score: "
            "CRITICAL (>=0.8) | HIGH (>=0.6) | MEDIUM (>=0.4) | LOW (<0.4)"
        ),
    )

    # ── 3. MITRE ATT&CK Mapping ──────────────────────────────────────────────
    #   technique_id   : e.g. "T1110.001"
    #   technique_name : e.g. "Brute Force: Password Guessing"
    #   tactic         : e.g. "Credential Access"
    #   mitre_url      : Official ATT&CK reference URL

    technique_id = Column(
        String(32),
        nullable=True,
        index=True,
        comment="MITRE ATT&CK technique ID, e.g. T1110.001",
    )

    technique_name = Column(
        String(256),
        nullable=True,
        comment="MITRE ATT&CK technique name, e.g. Brute Force: Password Guessing",
    )

    tactic = Column(
        String(128),
        nullable=True,
        comment="MITRE ATT&CK tactic name, e.g. Credential Access",
    )

    mitre_url = Column(
        String(512),
        nullable=True,
        comment="Official MITRE ATT&CK technique reference URL",
    )

    # ΓöÇΓöÇ 4. Detection Rules ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   snort_rule : Generated Snort IDS rule string (may be multi-line).
    #   sigma_rule : Generated Sigma detection rule in YAML format (reserved
    #                for Phase 6; nullable until rule_generator supports Sigma).

    snort_rule = Column(
        Text,
        nullable=True,
        comment="Generated Snort IDS rule string produced by rule_generator.py",
    )

    sigma_rule = Column(
        Text,
        nullable=True,
        comment="Generated Sigma YAML rule (reserved for Phase 6; currently null)",
    )

    # ΓöÇΓöÇ 5. Playbook Content ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   playbook_name    : Short descriptive name, e.g. "SSH Brute Force Response".
    #   playbook_content : Full rendered Jinja2 playbook Markdown/text body.
    #   template_name    : Name of the Jinja2 template used, e.g. "ssh_brute_force.j2".

    playbook_name = Column(
        String(256),
        nullable=True,
        comment="Short human-readable playbook title",
    )

    playbook_content = Column(
        Text,
        nullable=True,
        comment="Full rendered playbook body (Markdown format)",
    )

    template_name = Column(
        String(128),
        nullable=True,
        comment="Jinja2 template filename used to render playbook_content",
    )

    # ΓöÇΓöÇ 6. Lifecycle / Workflow ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    #   status      : Approval workflow state.
    #                 Values: "pending" | "approved" | "rejected" | "exported"
    #                 Default is "pending" ΓÇö all new playbooks await analyst review.
    #   reviewed_by : Username of the analyst who approved/rejected the playbook.
    #   reviewed_at : UTC timestamp of the approval/rejection action.

    status = Column(
        String(32),
        nullable=False,
        default="pending",
        index=True,
        comment="Workflow status: pending | approved | rejected | exported",
    )

    reviewed_by = Column(
        String(128),
        nullable=True,
        comment="Username of the analyst who approved or rejected this playbook",
    )

    reviewed_at = Column(
        DateTime,
        nullable=True,
        comment="UTC timestamp when the analyst reviewed this playbook",
    )

    # ΓöÇΓöÇ Helpers ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

    def __repr__(self) -> str:  # pragma: no cover
        """Return a developer-friendly string representation of the playbook record."""
        return (
            f"<SentinelPlaybook id={self.id} playbook_id={self.playbook_id!r} "
            f"attack_type={self.attack_type!r} confidence={self.confidence_score} "
            f"severity={self.severity!r} status={self.status!r}>"
        )

    def to_dict(self) -> Dict[str, Any]:
        """
        Serialize all 23 columns to a plain dictionary.

        Used by the REST API (api/sentinel.py) to build JSON responses without
        importing Pydantic schemas in the model layer.

        Returns:
            dict: All column values with ISO-8601 timestamps for datetime fields.
        """
        return {
            # Core Identity
            "id":               self.id,
            "playbook_id":      self.playbook_id,
            "created_at":       self.created_at.isoformat() if self.created_at else None,
            "updated_at":       self.updated_at.isoformat() if self.updated_at else None,
            # Threat Context
            "src_ip":           self.src_ip,
            "dst_port":         self.dst_port,
            "protocol":         self.protocol,
            "attack_type":      self.attack_type,
            "threat_score":     self.threat_score,
            "confidence_score": self.confidence_score,
            "severity":         self.severity,
            # MITRE ATT&CK
            "technique_id":     self.technique_id,
            "technique_name":   self.technique_name,
            "tactic":           self.tactic,
            "mitre_url":        self.mitre_url,
            # Detection Rules
            "snort_rule":       self.snort_rule,
            "sigma_rule":       self.sigma_rule,
            # Playbook Content
            "playbook_name":    self.playbook_name,
            "playbook_content": self.playbook_content,
            "template_name":    self.template_name,
            # Lifecycle
            "status":           self.status,
            "reviewed_by":      self.reviewed_by,
            "reviewed_at":      self.reviewed_at.isoformat() if self.reviewed_at else None,
        }
