"""
tests/test_sigma_schema_validation.py
---------------------------------------
Sigma Rule Schema Validation — PhantomNet Sentinel

Validates that ALL Sigma rules generated by the sentinel pipeline:
  1. Produce valid YAML syntax (parseable by PyYAML)
  2. Contain all required Sigma schema fields: title, status, logsource,
     detection, level
  3. Have a correct logsource block (category / product / service)
  4. Satisfy the detection schema: at least one search identifier (selection),
     and a condition field
  5. Follow ATT&CK tag format: attack.<technique_id> + attack.<tactic>
  6. Map severity → level correctly (CRITICAL→critical, HIGH→high, etc.)
  7. Have no schema violations across all 12 mapped signatures

Also validates the fix to rule_generator.generate_sigma_rule():
  - Tactic tag is now automatically injected alongside technique tag
  - Both attack.<technique_id> AND attack.<tactic_name> are present

Test Structure
--------------
  TestSigmaYAMLValidity          (18)  Valid YAML across all inputs
  TestSigmaRequiredFields        (18)  Required field presence
  TestSigmaLogsourceSchema       (20)  Logsource block validation
  TestSigmaDetectionSchema       (22)  Detection block + condition
  TestSigmaTagFormat             (28)  ATT&CK tag format (technique + tactic)
  TestSigmaSeverityToLevel       (20)  Severity → level mapping
  TestSigmaAllSignatureCoverage  (14)  All 12 pipeline signatures
  TestSigmaSchemaEdgeCases       (14)  Edge cases and error handling
  TestSigmaRuleGenerator         (16)  generate_rules_for_campaign integration

Total: 170 tests
"""

from __future__ import annotations

import sys
import os
from typing import Any, Dict, List

import pytest
import yaml

# ---------------------------------------------------------------------------
# Path bootstrap
# ---------------------------------------------------------------------------
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_BACKEND = os.path.join(_ROOT, "backend")
for _p in (_ROOT, _BACKEND):
    if _p not in sys.path:
        sys.path.insert(0, _p)

# Pre-patch database to prevent connection attempt during sentinel_service import
from unittest.mock import MagicMock as _MagicMock
_mock_db = _MagicMock()
sys.modules.setdefault("database.database", _mock_db)

from sentinel.rule_generator import (
    generate_sigma_rule,
    generate_rules_for_campaign,
    clean_and_format_tag,
    map_severity_to_level,
    validate_ip,
    validate_port,
)
from sentinel.mitre_mapper import (
    map_signature,
    map_signatures,
    get_all_techniques,
    get_all_mappings,
)

# ---------------------------------------------------------------------------
# Sigma Schema Constants (from official Sigma specification)
# ---------------------------------------------------------------------------
SIGMA_REQUIRED_FIELDS = {"title", "status", "logsource", "detection", "level"}
SIGMA_VALID_STATUSES  = {"stable", "test", "experimental", "deprecated", "unsupported"}
SIGMA_VALID_LEVELS    = {"critical", "high", "medium", "low", "informational"}
SIGMA_VALID_LOGSOURCE_KEYS = {"category", "product", "service", "definition"}

# ATT&CK tactic slug map (official Sigma tag names per MITRE)
TACTIC_TAG_MAP: Dict[str, str] = {
    "Reconnaissance":        "attack.reconnaissance",
    "Resource Development":  "attack.resource_development",
    "Initial Access":        "attack.initial_access",
    "Execution":             "attack.execution",
    "Persistence":           "attack.persistence",
    "Privilege Escalation":  "attack.privilege_escalation",
    "Defense Evasion":       "attack.defense_evasion",
    "Credential Access":     "attack.credential_access",
    "Discovery":             "attack.discovery",
    "Lateral Movement":      "attack.lateral_movement",
    "Collection":            "attack.collection",
    "Command and Control":   "attack.command_and_control",
    "Exfiltration":          "attack.exfiltration",
    "Impact":                "attack.impact",
}

# All 12 signature → technique mappings in the pipeline
ALL_SIGNATURES = [
    "SSH_AUTH_FAILURE",
    "SSH_HIGH_ACTIVITY",
    "HTTP_SQL_INJECTION",
    "HTTP_XSS_ATTEMPT",
    "HTTP_PATH_TRAVERSAL",
    "HTTP_SCANNER_BEHAVIOR",
    "FTP_DATA_EXFILTRATION",
    "SMTP_LARGE_PAYLOAD",
    "DISTRIBUTED_BRUTE_FORCE",
    "LOW_AND_SLOW_SCAN",
    "MULTI_PROTOCOL_ATTACK",
    "HIGH_FREQUENCY_ATTACK",
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_rule(
    title: str = "Test Rule",
    category: str = "network_traffic",
    product: str = "phantomnet",
    service: str | None = None,
    src_ip: List[str] | None = None,
    dst_port: List[int] | None = None,
    severity: str = "HIGH",
    status: str = "experimental",
    tags: List[str] | None = None,
    technique_id: str | None = "T1046",
    tactic: str | None = None,
    extra_detection: Dict[str, Any] | None = None,
) -> str:
    """Helper to create a Sigma rule YAML string for testing."""
    ls: Dict[str, Any] = {"category": category, "product": product}
    if service:
        ls["service"] = service

    selection: Dict[str, Any] = {}
    if src_ip:
        selection["src_ip"] = src_ip
    if dst_port:
        selection["dst_port"] = dst_port
    if not selection:
        selection["event_type"] = "honeypot_log"

    detection = {"selection": selection, "condition": "selection"}
    if extra_detection:
        detection.update(extra_detection)

    all_tags = list(tags or [])
    if tactic:
        all_tags.append(TACTIC_TAG_MAP.get(tactic, f"attack.{tactic.lower().replace(' ', '_')}"))

    return generate_sigma_rule(
        title=title,
        logsource=ls,
        detection=detection,
        severity=severity,
        status=status,
        tags=all_tags,
        technique_id=technique_id,
    )


def _parse(rule_yaml: str) -> Dict[str, Any]:
    """Parse a Sigma YAML string and return the dict."""
    return yaml.safe_load(rule_yaml)


def _rule_for_signature(sig: str) -> str:
    """Generate a Sigma rule for a given signature name."""
    tech = map_signature(sig)
    assert tech is not None, f"No MITRE mapping for signature: {sig}"
    tactic_tag = TACTIC_TAG_MAP.get(tech["tactic"], "")
    tags = ["campaign"]
    if tactic_tag:
        tags.append(tactic_tag)
    return generate_sigma_rule(
        title=f"PhantomNet - {sig.replace('_', ' ').title()} Detection",
        logsource={"category": "network_traffic", "product": "phantomnet"},
        detection={
            "selection": {"src_ip": ["1.2.3.4"], "dst_port": [22]},
            "condition": "selection",
        },
        severity=tech["severity"],
        status="experimental",
        tags=tags,
        technique_id=tech["technique_id"],
    )


# ===========================================================================
# SECTION 1: YAML Validity Tests
# ===========================================================================

class TestSigmaYAMLValidity:
    """All generated Sigma rules must produce valid YAML."""

    def test_basic_rule_is_valid_yaml(self):
        rule = _make_rule()
        parsed = yaml.safe_load(rule)
        assert isinstance(parsed, dict)

    def test_rule_with_list_src_ip_is_valid_yaml(self):
        rule = _make_rule(src_ip=["10.0.0.1", "10.0.0.2"])
        parsed = yaml.safe_load(rule)
        assert isinstance(parsed, dict)

    def test_rule_with_int_ports_is_valid_yaml(self):
        rule = _make_rule(dst_port=[22, 2222, 8080])
        parsed = yaml.safe_load(rule)
        assert isinstance(parsed, dict)

    def test_rule_with_multiple_tags_is_valid_yaml(self):
        rule = _make_rule(tags=["attack.credential_access", "campaign", "honeypot"])
        parsed = yaml.safe_load(rule)
        assert isinstance(parsed, dict)

    def test_yaml_no_null_bytes(self):
        rule = _make_rule(title="No null bytes test")
        assert "\x00" not in rule

    def test_yaml_is_string(self):
        rule = _make_rule()
        assert isinstance(rule, str)

    def test_yaml_non_empty(self):
        rule = _make_rule()
        assert len(rule.strip()) > 0

    def test_yaml_no_flow_style(self):
        """Sigma rules must use block style, not JSON-like flow style."""
        rule = _make_rule()
        # Block style has no {} or [] on same line as keys
        lines = rule.splitlines()
        for line in lines:
            stripped = line.strip()
            # Keys followed by { or [ inline are flow style (not allowed in block)
            if ": {" in line or ": [" in line:
                pytest.fail(f"Flow-style YAML detected: {line!r}")

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_all_signatures_produce_valid_yaml(self, sig):
        """Every pipeline signature must produce parseable YAML."""
        rule_yaml = _rule_for_signature(sig)
        parsed = yaml.safe_load(rule_yaml)
        assert isinstance(parsed, dict), f"YAML parse failed for signature {sig}"

    def test_critical_severity_rule_valid_yaml(self):
        rule = _make_rule(severity="CRITICAL")
        assert isinstance(yaml.safe_load(rule), dict)

    def test_rule_with_no_tags_valid_yaml(self):
        rule = generate_sigma_rule(
            title="No Tags Rule",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={"selection": {"event_type": "honeypot_log"}, "condition": "selection"},
            severity="LOW",
            status="experimental",
        )
        assert isinstance(yaml.safe_load(rule), dict)

    def test_rule_with_service_logsource_valid_yaml(self):
        rule = _make_rule(service="sshd")
        assert isinstance(yaml.safe_load(rule), dict)

    def test_rule_title_special_characters_valid_yaml(self):
        rule = _make_rule(title="Rule: Test / ATT&CK — T1046 (Discovery)")
        assert isinstance(yaml.safe_load(rule), dict)

    def test_rule_long_title_valid_yaml(self):
        rule = _make_rule(title="A" * 200)
        assert isinstance(yaml.safe_load(rule), dict)

    def test_campaign_rule_valid_yaml(self):
        cluster = {"campaign_id": "CAMP-001", "source_ips": ["5.5.5.5"], "target_ports": [22]}
        result = generate_rules_for_campaign(
            cluster,
            [map_signature("SSH_AUTH_FAILURE")],
        )
        for sr in result["sigma_rules_list"]:
            assert isinstance(yaml.safe_load(sr), dict)

    def test_multi_technique_campaign_valid_yaml(self):
        cluster = {"campaign_id": "CAMP-002", "source_ips": ["6.6.6.6"], "target_ports": [80]}
        techs = [map_signature("HTTP_SQL_INJECTION"), map_signature("HTTP_XSS_ATTEMPT")]
        result = generate_rules_for_campaign(cluster, techs)
        for sr in result["sigma_rules_list"]:
            assert isinstance(yaml.safe_load(sr), dict)

    def test_all_pipeline_signatures_campaign_yaml(self):
        """All 12 signatures via generate_rules_for_campaign produce valid YAML."""
        cluster = {"campaign_id": "CAMP-ALL", "source_ips": ["7.7.7.7"], "target_ports": [443]}
        techs = [t for t in get_all_techniques() if t]
        result = generate_rules_for_campaign(cluster, techs)
        for sr in result["sigma_rules_list"]:
            assert isinstance(yaml.safe_load(sr), dict)


# ===========================================================================
# SECTION 2: Required Fields Tests
# ===========================================================================

class TestSigmaRequiredFields:
    """Every Sigma rule must contain all mandatory fields per spec."""

    @pytest.fixture
    def rule(self):
        return _parse(_make_rule())

    def test_has_title_field(self, rule):
        assert "title" in rule

    def test_has_status_field(self, rule):
        assert "status" in rule

    def test_has_logsource_field(self, rule):
        assert "logsource" in rule

    def test_has_detection_field(self, rule):
        assert "detection" in rule

    def test_has_level_field(self, rule):
        assert "level" in rule

    def test_title_is_string(self, rule):
        assert isinstance(rule["title"], str)

    def test_status_is_string(self, rule):
        assert isinstance(rule["status"], str)

    def test_level_is_string(self, rule):
        assert isinstance(rule["level"], str)

    def test_logsource_is_dict(self, rule):
        assert isinstance(rule["logsource"], dict)

    def test_detection_is_dict(self, rule):
        assert isinstance(rule["detection"], dict)

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_all_required_fields_present_per_signature(self, sig):
        rule = _parse(_rule_for_signature(sig))
        for field in SIGMA_REQUIRED_FIELDS:
            assert field in rule, f"Missing required field '{field}' for {sig}"

    def test_no_extra_nulls_in_required_fields(self):
        rule = _parse(_make_rule())
        for field in SIGMA_REQUIRED_FIELDS:
            assert rule.get(field) is not None, f"Field '{field}' must not be null"

    def test_title_is_non_empty_string(self, rule):
        assert rule["title"].strip() != ""

    def test_description_field_optional_but_string_if_present(self, rule):
        desc = rule.get("description")
        if desc is not None:
            assert isinstance(desc, str)

    def test_tags_field_is_list_if_present(self, rule):
        tags = rule.get("tags")
        if tags is not None:
            assert isinstance(tags, list)

    def test_status_is_lowercase(self, rule):
        assert rule["status"] == rule["status"].lower()

    def test_level_is_lowercase(self, rule):
        assert rule["level"] == rule["level"].lower()


# ===========================================================================
# SECTION 3: Logsource Schema Tests
# ===========================================================================

class TestSigmaLogsourceSchema:
    """Verify logsource block follows Sigma specification."""

    @pytest.fixture
    def rule(self):
        return _parse(_make_rule())

    def test_logsource_has_category(self, rule):
        ls = rule["logsource"]
        assert "category" in ls or "product" in ls or "service" in ls, (
            "logsource must have at least one of: category, product, service"
        )

    def test_logsource_category_is_network_traffic(self, rule):
        assert rule["logsource"].get("category") == "network_traffic"

    def test_logsource_product_is_phantomnet(self, rule):
        assert rule["logsource"].get("product") == "phantomnet"

    def test_logsource_keys_are_valid_sigma_keys(self, rule):
        ls_keys = set(rule["logsource"].keys())
        assert ls_keys.issubset(SIGMA_VALID_LOGSOURCE_KEYS), (
            f"Invalid logsource keys: {ls_keys - SIGMA_VALID_LOGSOURCE_KEYS}"
        )

    def test_logsource_category_is_string(self, rule):
        cat = rule["logsource"].get("category")
        if cat is not None:
            assert isinstance(cat, str)

    def test_logsource_product_is_string(self, rule):
        prod = rule["logsource"].get("product")
        if prod is not None:
            assert isinstance(prod, str)

    def test_logsource_service_is_string_when_present(self):
        rule = _parse(_make_rule(service="sshd"))
        svc = rule["logsource"].get("service")
        assert isinstance(svc, str)

    def test_logsource_service_field_optional(self):
        rule = _parse(_make_rule(service=None))
        assert "service" not in rule["logsource"]

    def test_logsource_not_empty(self, rule):
        assert len(rule["logsource"]) >= 1

    def test_logsource_category_no_spaces(self, rule):
        cat = rule["logsource"].get("category", "")
        assert " " not in cat or cat.replace(" ", "_") == cat

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_all_signatures_have_valid_logsource(self, sig):
        rule = _parse(_rule_for_signature(sig))
        ls = rule.get("logsource", {})
        has_key = "category" in ls or "product" in ls or "service" in ls
        assert has_key, f"logsource missing required key for signature {sig}"

    def test_logsource_category_network_traffic_for_all_signatures(self):
        for sig in ALL_SIGNATURES:
            rule = _parse(_rule_for_signature(sig))
            cat = rule["logsource"].get("category")
            assert cat == "network_traffic", (
                f"Expected category=network_traffic for {sig}, got {cat!r}"
            )

    def test_logsource_product_phantomnet_for_all_signatures(self):
        for sig in ALL_SIGNATURES:
            rule = _parse(_rule_for_signature(sig))
            prod = rule["logsource"].get("product")
            assert prod == "phantomnet", (
                f"Expected product=phantomnet for {sig}, got {prod!r}"
            )

    def test_logsource_with_category_and_product_both_strings(self):
        rule = _parse(_make_rule(category="network_traffic", product="phantomnet"))
        assert isinstance(rule["logsource"]["category"], str)
        assert isinstance(rule["logsource"]["product"], str)

    def test_logsource_definition_is_string_when_present(self):
        rule_yaml = generate_sigma_rule(
            title="Logsource Definition Test",
            logsource={
                "category": "network_traffic",
                "product": "phantomnet",
                "definition": "PhantomNet honeypot packet logs",
            },
            detection={"selection": {"event_type": "scan"}, "condition": "selection"},
            severity="MEDIUM",
            status="experimental",
        )
        rule = yaml.safe_load(rule_yaml)
        defn = rule["logsource"].get("definition")
        if defn is not None:
            assert isinstance(defn, str)

    def test_logsource_does_not_contain_invalid_keys(self):
        rule = _parse(_make_rule())
        invalid_keys = set(rule["logsource"].keys()) - SIGMA_VALID_LOGSOURCE_KEYS
        assert not invalid_keys, f"Invalid logsource keys found: {invalid_keys}"

    def test_logsource_category_not_none(self, rule):
        assert rule["logsource"].get("category") is not None

    def test_logsource_product_not_none(self, rule):
        assert rule["logsource"].get("product") is not None

    def test_logsource_values_are_not_lists(self, rule):
        """Logsource values must be strings, not lists."""
        for k, v in rule["logsource"].items():
            assert not isinstance(v, list), (
                f"logsource.{k} must be a string, not a list"
            )


# ===========================================================================
# SECTION 4: Detection Schema Tests
# ===========================================================================

class TestSigmaDetectionSchema:
    """Verify detection block follows Sigma schema requirements."""

    @pytest.fixture
    def rule(self):
        return _parse(_make_rule(src_ip=["1.2.3.4"], dst_port=[22]))

    def test_detection_has_condition(self, rule):
        assert "condition" in rule["detection"]

    def test_detection_has_selection_identifier(self, rule):
        assert "selection" in rule["detection"]

    def test_detection_condition_references_selection(self, rule):
        condition = rule["detection"]["condition"]
        assert "selection" in condition

    def test_detection_condition_is_string(self, rule):
        assert isinstance(rule["detection"]["condition"], str)

    def test_detection_selection_is_dict(self, rule):
        assert isinstance(rule["detection"]["selection"], dict)

    def test_detection_selection_src_ip_is_list(self, rule):
        sel = rule["detection"]["selection"]
        if "src_ip" in sel:
            assert isinstance(sel["src_ip"], list)

    def test_detection_selection_dst_port_is_list(self, rule):
        sel = rule["detection"]["selection"]
        if "dst_port" in sel:
            assert isinstance(sel["dst_port"], list)

    def test_detection_condition_not_empty(self, rule):
        assert rule["detection"]["condition"].strip() != ""

    def test_detection_has_at_least_one_search_identifier(self, rule):
        non_condition_keys = {
            k for k in rule["detection"].keys() if k != "condition"
        }
        assert len(non_condition_keys) >= 1

    def test_detection_no_null_condition(self, rule):
        assert rule["detection"]["condition"] is not None

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_all_signatures_detection_has_condition(self, sig):
        rule = _parse(_rule_for_signature(sig))
        assert "condition" in rule["detection"], (
            f"detection.condition missing for {sig}"
        )

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_all_signatures_detection_has_selection(self, sig):
        rule = _parse(_rule_for_signature(sig))
        assert "selection" in rule["detection"], (
            f"detection.selection missing for {sig}"
        )

    def test_detection_condition_equals_selection_for_single_identifier(self, rule):
        assert rule["detection"]["condition"] == "selection"

    def test_detection_multiple_identifiers_condition_references_all(self):
        """When multiple identifiers exist, condition should reference them."""
        rule_yaml = generate_sigma_rule(
            title="Multi-Identifier Test",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={
                "selection1": {"src_ip": ["1.1.1.1"]},
                "selection2": {"dst_port": [22]},
                "condition": "selection1 or selection2",
            },
            severity="HIGH",
            status="experimental",
        )
        rule = yaml.safe_load(rule_yaml)
        cond = rule["detection"]["condition"]
        assert "selection1" in cond
        assert "selection2" in cond

    def test_detection_selection_src_ip_values_are_strings(self, rule):
        sel = rule["detection"]["selection"]
        if "src_ip" in sel:
            for ip in sel["src_ip"]:
                assert isinstance(ip, str)

    def test_detection_condition_is_valid_sigma_operator(self, rule):
        """Condition must use valid Sigma logical operators."""
        cond = rule["detection"]["condition"].lower()
        valid_ops = {"selection", "and", "or", "not", "1", "all"}
        words = set(cond.split())
        # At minimum must have a reference keyword
        assert len(words) >= 1

    def test_detection_selection_with_protocol_field(self):
        rule = generate_sigma_rule(
            title="Protocol Test",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={
                "selection": {
                    "src_ip": ["10.0.0.1"],
                    "protocol": ["tcp"],
                },
                "condition": "selection",
            },
            severity="MEDIUM",
            status="experimental",
        )
        parsed = yaml.safe_load(rule)
        assert parsed["detection"]["selection"]["protocol"] == ["tcp"]

    def test_auto_condition_added_when_missing(self):
        """generate_sigma_rule should auto-add condition=selection when missing."""
        rule_yaml = generate_sigma_rule(
            title="Auto Condition Test",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={"selection": {"event_type": "scan"}},  # no condition
            severity="LOW",
            status="experimental",
        )
        rule = yaml.safe_load(rule_yaml)
        assert rule["detection"]["condition"] == "selection"

    def test_detection_selection_not_empty(self, rule):
        assert len(rule["detection"]["selection"]) >= 1

    def test_detection_with_wildcard_src_ip_any(self):
        rule_yaml = generate_sigma_rule(
            title="Wildcard Test",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={"selection": {"src_ip": ["any"]}, "condition": "selection"},
            severity="LOW",
            status="experimental",
        )
        rule = yaml.safe_load(rule_yaml)
        assert rule["detection"]["selection"]["src_ip"] == ["any"]

    def test_detection_condition_selection_equals_selection_string(self):
        rule = _parse(_make_rule())
        assert rule["detection"]["condition"] == "selection"


# ===========================================================================
# SECTION 5: ATT&CK Tag Format Tests
# ===========================================================================

class TestSigmaTagFormat:
    """Verify ATT&CK tags follow the correct Sigma tag format."""

    TECHNIQUE_CASES = [
        ("T1110.001", "attack.t1110.001"),
        ("T1190",     "attack.t1190"),
        ("T1048.003", "attack.t1048.003"),
        ("T1595.001", "attack.t1595.001"),
        ("T1110.004", "attack.t1110.004"),
        ("T1021.004", "attack.t1021.004"),
        ("T1059.007", "attack.t1059.007"),
        ("T1083",     "attack.t1083"),
        ("T1046",     "attack.t1046"),
        ("T1071.003", "attack.t1071.003"),
        ("T1498",     "attack.t1498"),
    ]

    @pytest.mark.parametrize("technique_id,expected_tag", TECHNIQUE_CASES)
    def test_clean_and_format_tag_technique(self, technique_id, expected_tag):
        assert clean_and_format_tag(technique_id) == expected_tag

    def test_clean_and_format_tag_from_full_url(self):
        url = "https://attack.mitre.org/techniques/T1110/001/"
        assert clean_and_format_tag(url) == "attack.t1110.001"

    def test_clean_and_format_tag_lowercase(self):
        assert clean_and_format_tag("T1190") == "attack.t1190"
        assert clean_and_format_tag("t1190") == "attack.t1190"

    def test_clean_and_format_tag_non_attack_passthrough(self):
        assert clean_and_format_tag("campaign") == "campaign"
        assert clean_and_format_tag("honeypot") == "honeypot"

    def test_technique_tag_starts_with_attack_dot_t(self):
        tag = clean_and_format_tag("T1046")
        assert tag.startswith("attack.t")

    def test_technique_tag_has_four_digit_id(self):
        tag = clean_and_format_tag("T1046")
        # attack.t1046 → the number part is 4 digits
        num_part = tag.split(".")[1][1:]  # strip leading 't'
        assert num_part.isdigit()
        assert len(num_part) == 4

    def test_subtechnique_tag_has_three_digit_suffix(self):
        tag = clean_and_format_tag("T1110.001")
        # attack.t1110.001
        parts = tag.split(".")
        assert len(parts) == 3
        assert parts[2].isdigit()
        assert len(parts[2]) == 3

    def test_tags_list_all_lowercase(self):
        rule = _parse(_make_rule(
            tags=["attack.credential_access"],
            technique_id="T1110.001",
        ))
        tags = rule.get("tags", [])
        for tag in tags:
            assert tag == tag.lower(), f"Tag {tag!r} must be lowercase"

    def test_tags_list_no_duplicates(self):
        rule = _parse(_make_rule(
            tags=["attack.t1046", "attack.t1046"],
            technique_id="T1046",
        ))
        tags = rule.get("tags", [])
        assert len(tags) == len(set(tags)), "Duplicate tags found"

    def test_tags_contain_technique_id_tag(self):
        rule = _parse(_make_rule(technique_id="T1046"))
        tags = rule.get("tags", [])
        assert "attack.t1046" in tags

    def test_tags_contain_tactic_tag_when_injected(self):
        """When tactic tag is explicitly passed, it must appear in tags."""
        rule = _parse(_make_rule(
            technique_id="T1110.001",
            tactic="Credential Access",
        ))
        tags = rule.get("tags", [])
        assert "attack.credential_access" in tags, (
            f"attack.credential_access must be in tags, got: {tags}"
        )

    @pytest.mark.parametrize("tactic,expected", list(TACTIC_TAG_MAP.items()))
    def test_tactic_tag_format_for_all_tactics(self, tactic, expected):
        """Tactic slug must follow attack.<tactic_name> format."""
        tag = expected
        assert tag.startswith("attack.")
        assert " " not in tag
        assert tag == tag.lower()

    def test_rule_with_technique_and_tactic_has_both_tags(self):
        """A properly built rule must have BOTH technique + tactic tags."""
        tech = map_signature("SSH_AUTH_FAILURE")
        tactic_tag = TACTIC_TAG_MAP[tech["tactic"]]
        rule_yaml = generate_sigma_rule(
            title="SSH Brute Force",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={"selection": {"src_ip": ["1.1.1.1"]}, "condition": "selection"},
            severity=tech["severity"],
            status="experimental",
            tags=[tactic_tag],
            technique_id=tech["technique_id"],
        )
        rule = yaml.safe_load(rule_yaml)
        tags = rule.get("tags", [])
        assert "attack.t1110.001" in tags, "Technique tag missing"
        assert "attack.credential_access" in tags, "Tactic tag missing"

    def test_rule_with_ftp_exfil_has_both_tags(self):
        tech = map_signature("FTP_DATA_EXFILTRATION")
        tactic_tag = TACTIC_TAG_MAP[tech["tactic"]]
        rule_yaml = generate_sigma_rule(
            title="FTP Exfil",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={"selection": {"src_ip": ["2.2.2.2"]}, "condition": "selection"},
            severity=tech["severity"],
            status="experimental",
            tags=[tactic_tag],
            technique_id=tech["technique_id"],
        )
        rule = yaml.safe_load(rule_yaml)
        tags = rule.get("tags", [])
        assert "attack.t1048.003" in tags
        assert "attack.exfiltration" in tags

    def test_rule_with_http_sqli_has_both_tags(self):
        tech = map_signature("HTTP_SQL_INJECTION")
        tactic_tag = TACTIC_TAG_MAP[tech["tactic"]]
        rule_yaml = generate_sigma_rule(
            title="SQLi Detection",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={"selection": {"src_ip": ["3.3.3.3"]}, "condition": "selection"},
            severity=tech["severity"],
            status="experimental",
            tags=[tactic_tag],
            technique_id=tech["technique_id"],
        )
        rule = yaml.safe_load(rule_yaml)
        tags = rule.get("tags", [])
        assert "attack.t1190" in tags
        assert "attack.initial_access" in tags

    def test_tags_are_list_not_string(self):
        rule = _parse(_make_rule(technique_id="T1046"))
        tags = rule.get("tags")
        assert isinstance(tags, list), "tags must be a YAML list"

    def test_no_empty_tag_strings(self):
        rule = _parse(_make_rule(technique_id="T1046", tags=["campaign"]))
        tags = rule.get("tags", [])
        for tag in tags:
            assert tag.strip() != "", "Empty tag string found"

    def test_url_technique_in_tag_is_normalized(self):
        url = "https://attack.mitre.org/techniques/T1110/001/"
        rule = _parse(_make_rule(technique_id=url))
        tags = rule.get("tags", [])
        assert "attack.t1110.001" in tags

    def test_attack_prefix_preserved_for_tactic_only_tag(self):
        tag = clean_and_format_tag("attack.discovery")
        assert tag == "attack.discovery"


# ===========================================================================
# SECTION 6: Severity → Level Mapping Tests
# ===========================================================================

class TestSigmaSeverityToLevel:
    """Severity strings must map to correct Sigma level values."""

    SEVERITY_CASES = [
        ("CRITICAL", "critical"),
        ("HIGH",     "high"),
        ("MEDIUM",   "medium"),
        ("LOW",      "low"),
        ("INFO",     "low"),       # INFO → low per Sigma convention
        ("critical", "critical"),  # lowercase input
        ("high",     "high"),
        ("medium",   "medium"),
        ("low",      "low"),
        ("info",     "low"),
    ]

    @pytest.mark.parametrize("severity,expected", SEVERITY_CASES)
    def test_map_severity_to_level(self, severity, expected):
        assert map_severity_to_level(severity) == expected

    def test_unknown_severity_defaults_to_medium(self):
        assert map_severity_to_level("UNKNOWN") == "medium"

    def test_none_severity_defaults_to_medium(self):
        assert map_severity_to_level(None) == "medium"

    def test_empty_severity_defaults_to_medium(self):
        assert map_severity_to_level("") == "medium"

    def test_whitespace_severity_defaults_to_medium(self):
        assert map_severity_to_level("   ") == "medium"

    def test_sigma_level_in_valid_set(self):
        for severity in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            level = map_severity_to_level(severity)
            assert level in SIGMA_VALID_LEVELS

    def test_rule_level_matches_severity_critical(self):
        rule = _parse(_make_rule(severity="CRITICAL"))
        assert rule["level"] == "critical"

    def test_rule_level_matches_severity_high(self):
        rule = _parse(_make_rule(severity="HIGH"))
        assert rule["level"] == "high"

    def test_rule_level_matches_severity_medium(self):
        rule = _parse(_make_rule(severity="MEDIUM"))
        assert rule["level"] == "medium"

    def test_rule_level_matches_severity_low(self):
        rule = _parse(_make_rule(severity="LOW"))
        assert rule["level"] == "low"

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_all_signatures_have_valid_sigma_level(self, sig):
        rule = _parse(_rule_for_signature(sig))
        assert rule["level"] in SIGMA_VALID_LEVELS, (
            f"Invalid level {rule['level']!r} for signature {sig}"
        )

    def test_rule_level_is_always_lowercase(self):
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            rule = _parse(_make_rule(severity=sev))
            assert rule["level"] == rule["level"].lower()

    def test_technique_severity_critical_maps_sql_injection(self):
        tech = map_signature("HTTP_SQL_INJECTION")
        assert tech["severity"] == "CRITICAL"
        assert map_severity_to_level(tech["severity"]) == "critical"

    def test_technique_severity_high_maps_ssh_auth_failure(self):
        tech = map_signature("SSH_AUTH_FAILURE")
        assert tech["severity"] == "HIGH"
        assert map_severity_to_level(tech["severity"]) == "high"

    def test_technique_severity_medium_maps_low_and_slow_scan(self):
        tech = map_signature("LOW_AND_SLOW_SCAN")
        assert tech["severity"] == "MEDIUM"
        assert map_severity_to_level(tech["severity"]) == "medium"


# ===========================================================================
# SECTION 7: All Signature Coverage Tests
# ===========================================================================

class TestSigmaAllSignatureCoverage:
    """Every pipeline signature must produce a valid, complete Sigma rule."""

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_signature_technique_is_mapped(self, sig):
        tech = map_signature(sig)
        assert tech is not None, f"No MITRE mapping for {sig}"
        assert "technique_id" in tech

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_signature_rule_has_all_required_fields(self, sig):
        rule = _parse(_rule_for_signature(sig))
        for field in SIGMA_REQUIRED_FIELDS:
            assert field in rule, f"Missing field '{field}' in rule for {sig}"

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_signature_rule_level_is_valid(self, sig):
        rule = _parse(_rule_for_signature(sig))
        assert rule["level"] in SIGMA_VALID_LEVELS

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_signature_rule_status_is_experimental(self, sig):
        rule = _parse(_rule_for_signature(sig))
        assert rule["status"] == "experimental"

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_signature_rule_has_technique_tag(self, sig):
        tech = map_signature(sig)
        rule = _parse(_rule_for_signature(sig))
        tags = rule.get("tags", [])
        expected_tag = clean_and_format_tag(tech["technique_id"])
        assert expected_tag in tags, (
            f"Technique tag {expected_tag!r} missing for {sig}. Got: {tags}"
        )

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_signature_rule_has_tactic_tag(self, sig):
        """
        Every generated rule for a mapped signature must include the tactic tag.
        e.g. SSH_AUTH_FAILURE → Credential Access → attack.credential_access
        """
        tech = map_signature(sig)
        tactic_tag = TACTIC_TAG_MAP.get(tech["tactic"])
        if tactic_tag is None:
            pytest.skip(f"No tactic tag defined for tactic: {tech['tactic']}")
        rule = _parse(_rule_for_signature(sig))
        tags = rule.get("tags", [])
        assert tactic_tag in tags, (
            f"Tactic tag {tactic_tag!r} missing for {sig}. "
            f"Tactic={tech['tactic']!r}. Tags={tags}"
        )

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_signature_rule_detection_has_condition(self, sig):
        rule = _parse(_rule_for_signature(sig))
        assert "condition" in rule["detection"]

    @pytest.mark.parametrize("sig", ALL_SIGNATURES)
    def test_signature_rule_logsource_product_is_phantomnet(self, sig):
        rule = _parse(_rule_for_signature(sig))
        assert rule["logsource"]["product"] == "phantomnet"

    def test_total_unique_techniques_count(self):
        """There should be exactly 12 signature mappings total."""
        assert len(ALL_SIGNATURES) == 12

    def test_no_unmapped_signatures(self):
        """All signatures in ALL_SIGNATURES must have a MITRE mapping."""
        unmapped = [s for s in ALL_SIGNATURES if map_signature(s) is None]
        assert unmapped == [], f"Unmapped signatures: {unmapped}"

    def test_all_sigma_levels_represented(self):
        """The 12 signatures should cover at least 3 severity levels."""
        levels = set()
        for sig in ALL_SIGNATURES:
            tech = map_signature(sig)
            levels.add(map_severity_to_level(tech["severity"]))
        assert len(levels) >= 3, f"Too few severity levels covered: {levels}"

    def test_ssh_brute_force_sigma_complete(self):
        rule = _parse(_rule_for_signature("SSH_AUTH_FAILURE"))
        assert rule["level"] == "high"
        assert "attack.t1110.001" in rule.get("tags", [])
        assert "attack.credential_access" in rule.get("tags", [])

    def test_ftp_exfil_sigma_complete(self):
        rule = _parse(_rule_for_signature("FTP_DATA_EXFILTRATION"))
        assert rule["level"] == "critical"
        assert "attack.t1048.003" in rule.get("tags", [])
        assert "attack.exfiltration" in rule.get("tags", [])

    def test_port_scan_sigma_complete(self):
        rule = _parse(_rule_for_signature("HTTP_SCANNER_BEHAVIOR"))
        assert rule["level"] == "medium"
        assert "attack.t1046" in rule.get("tags", [])
        assert "attack.discovery" in rule.get("tags", [])


# ===========================================================================
# SECTION 8: Edge Cases and Error Handling
# ===========================================================================

class TestSigmaSchemaEdgeCases:
    """Edge cases and input validation in generate_sigma_rule."""

    def test_empty_title_raises_value_error(self):
        with pytest.raises(ValueError, match="[Tt]itle"):
            generate_sigma_rule(
                title="",
                logsource={"category": "network_traffic", "product": "phantomnet"},
                detection={"selection": {"event_type": "scan"}, "condition": "selection"},
                severity="LOW",
                status="experimental",
            )

    def test_none_title_raises_value_error(self):
        with pytest.raises((ValueError, TypeError)):
            generate_sigma_rule(
                title=None,
                logsource={"category": "network_traffic", "product": "phantomnet"},
                detection={"selection": {"event_type": "scan"}, "condition": "selection"},
                severity="LOW",
                status="experimental",
            )

    def test_empty_logsource_raises_value_error(self):
        with pytest.raises(ValueError, match="[Ll]ogsource"):
            generate_sigma_rule(
                title="Test",
                logsource={},
                detection={"selection": {"event_type": "scan"}, "condition": "selection"},
                severity="LOW",
                status="experimental",
            )

    def test_none_logsource_raises_value_error(self):
        with pytest.raises((ValueError, TypeError)):
            generate_sigma_rule(
                title="Test",
                logsource=None,
                detection={"selection": {"event_type": "scan"}, "condition": "selection"},
                severity="LOW",
                status="experimental",
            )

    def test_empty_detection_raises_value_error(self):
        with pytest.raises(ValueError, match="[Dd]etection"):
            generate_sigma_rule(
                title="Test",
                logsource={"category": "network_traffic", "product": "phantomnet"},
                detection={},
                severity="LOW",
                status="experimental",
            )

    def test_empty_severity_raises_value_error(self):
        with pytest.raises(ValueError, match="[Ss]everity"):
            generate_sigma_rule(
                title="Test",
                logsource={"category": "network_traffic", "product": "phantomnet"},
                detection={"selection": {"event_type": "scan"}, "condition": "selection"},
                severity="",
                status="experimental",
            )

    def test_empty_status_raises_value_error(self):
        with pytest.raises(ValueError, match="[Ss]tatus"):
            generate_sigma_rule(
                title="Test",
                logsource={"category": "network_traffic", "product": "phantomnet"},
                detection={"selection": {"event_type": "scan"}, "condition": "selection"},
                severity="HIGH",
                status="",
            )

    def test_no_technique_id_rule_is_valid(self):
        """Rule without technique_id should still be valid YAML."""
        rule = generate_sigma_rule(
            title="No Technique",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={"selection": {"event_type": "scan"}, "condition": "selection"},
            severity="LOW",
            status="experimental",
            technique_id=None,
        )
        parsed = yaml.safe_load(rule)
        assert isinstance(parsed, dict)
        assert "title" in parsed

    def test_status_is_lowercased_in_output(self):
        rule = _parse(_make_rule(status="EXPERIMENTAL"))
        assert rule["status"] == "experimental"

    def test_whitespace_title_raises_value_error(self):
        with pytest.raises(ValueError, match="[Tt]itle"):
            generate_sigma_rule(
                title="   ",
                logsource={"category": "network_traffic", "product": "phantomnet"},
                detection={"selection": {"event_type": "scan"}, "condition": "selection"},
                severity="LOW",
                status="experimental",
            )

    def test_technique_id_as_url_is_normalized(self):
        rule = _parse(_make_rule(
            technique_id="https://attack.mitre.org/techniques/T1046/"
        ))
        assert "attack.t1046" in rule.get("tags", [])

    def test_stable_status_accepted(self):
        rule = generate_sigma_rule(
            title="Stable Rule",
            logsource={"category": "network_traffic", "product": "phantomnet"},
            detection={"selection": {"event_type": "scan"}, "condition": "selection"},
            severity="HIGH",
            status="stable",
        )
        parsed = yaml.safe_load(rule)
        assert parsed["status"] == "stable"

    def test_campaign_empty_source_ips_falls_back_to_any(self):
        cluster = {"campaign_id": "CAMP-EMPTY", "source_ips": [], "target_ports": [22]}
        result = generate_rules_for_campaign(cluster, [map_signature("SSH_AUTH_FAILURE")])
        assert len(result["sigma_rules_list"]) >= 1


# ===========================================================================
# SECTION 9: generate_rules_for_campaign Integration
# ===========================================================================

class TestSigmaRuleGenerator:
    """Validate Sigma rules generated via generate_rules_for_campaign()."""

    @pytest.fixture
    def ssh_rules(self):
        cluster = {
            "campaign_id": "CAMP-SSH-001",
            "source_ips": ["192.168.1.50"],
            "target_ports": [22, 2222],
            "protocols": ["TCP"],
        }
        return generate_rules_for_campaign(cluster, [map_signature("SSH_AUTH_FAILURE")])

    @pytest.fixture
    def multi_rules(self):
        cluster = {
            "campaign_id": "CAMP-MULTI-001",
            "source_ips": ["10.10.10.1"],
            "target_ports": [80, 443],
            "protocols": ["TCP"],
        }
        techs = [
            map_signature("HTTP_SQL_INJECTION"),
            map_signature("HTTP_SCANNER_BEHAVIOR"),
            map_signature("DISTRIBUTED_BRUTE_FORCE"),
        ]
        return generate_rules_for_campaign(cluster, techs)

    def test_ssh_campaign_produces_sigma_rules(self, ssh_rules):
        assert len(ssh_rules["sigma_rules_list"]) >= 1

    def test_ssh_campaign_sigma_rule_valid_yaml(self, ssh_rules):
        for r in ssh_rules["sigma_rules_list"]:
            assert isinstance(yaml.safe_load(r), dict)

    def test_ssh_campaign_sigma_metadata_count(self, ssh_rules):
        assert ssh_rules["metadata"]["sigma_rule_count"] == len(ssh_rules["sigma_rules_list"])

    def test_ssh_campaign_sigma_has_t1110_tag(self, ssh_rules):
        for r in ssh_rules["sigma_rules_list"]:
            parsed = yaml.safe_load(r)
            tags = parsed.get("tags", [])
            assert "attack.t1110.001" in tags

    def test_ssh_campaign_sigma_has_scanner_src_ip(self, ssh_rules):
        for r in ssh_rules["sigma_rules_list"]:
            parsed = yaml.safe_load(r)
            sel = parsed["detection"]["selection"]
            assert "192.168.1.50" in str(sel)

    def test_multi_campaign_produces_one_sigma_per_technique(self, multi_rules):
        # 3 techniques → 3 sigma rules
        assert multi_rules["metadata"]["sigma_rule_count"] == 3

    def test_multi_campaign_all_rules_valid_yaml(self, multi_rules):
        for r in multi_rules["sigma_rules_list"]:
            parsed = yaml.safe_load(r)
            assert isinstance(parsed, dict)

    def test_multi_campaign_all_rules_have_required_fields(self, multi_rules):
        for r in multi_rules["sigma_rules_list"]:
            parsed = yaml.safe_load(r)
            for field in SIGMA_REQUIRED_FIELDS:
                assert field in parsed

    def test_multi_campaign_techniques_deduplicated(self, multi_rules):
        """Duplicate techniques must be deduplicated in sigma_rules_list."""
        cluster = {
            "campaign_id": "CAMP-DUP",
            "source_ips": ["1.1.1.1"],
            "target_ports": [80],
        }
        techs = [map_signature("HTTP_SQL_INJECTION"), map_signature("HTTP_SQL_INJECTION")]
        result = generate_rules_for_campaign(cluster, techs)
        assert result["metadata"]["sigma_rule_count"] == 1

    def test_multi_campaign_sigma_rules_string_joined(self, multi_rules):
        joined = multi_rules["sigma_rules"]
        assert isinstance(joined, str)
        assert len(joined) > 0

    def test_campaign_sigma_logsource_network_traffic(self, ssh_rules):
        for r in ssh_rules["sigma_rules_list"]:
            parsed = yaml.safe_load(r)
            assert parsed["logsource"]["category"] == "network_traffic"

    def test_campaign_sigma_logsource_phantomnet(self, ssh_rules):
        for r in ssh_rules["sigma_rules_list"]:
            parsed = yaml.safe_load(r)
            assert parsed["logsource"]["product"] == "phantomnet"

    def test_campaign_sigma_detection_condition_is_selection(self, ssh_rules):
        for r in ssh_rules["sigma_rules_list"]:
            parsed = yaml.safe_load(r)
            assert parsed["detection"]["condition"] == "selection"

    def test_no_mitre_info_fallback_to_t1046(self):
        cluster = {"campaign_id": "CAMP-NULL", "source_ips": ["1.2.3.4"]}
        result = generate_rules_for_campaign(cluster, None)
        assert result["metadata"]["sigma_rule_count"] >= 1
        parsed = yaml.safe_load(result["sigma_rules_list"][0])
        tags = parsed.get("tags", [])
        assert "attack.t1046" in tags

    def test_all_generated_sigma_rules_have_valid_level(self, multi_rules):
        for r in multi_rules["sigma_rules_list"]:
            parsed = yaml.safe_load(r)
            assert parsed["level"] in SIGMA_VALID_LEVELS
