"""v3_baseline_schema

Revision ID: b38a3ae24623
Revises: 
Create Date: 2026-09-19 00:50:52.722032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38a3ae24623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_source_ip'), ['source_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_type'), ['type'], unique=False)

    op.create_table('attack_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_ip', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('threat_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attack_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attack_sessions_attacker_ip'), ['attacker_ip'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('investigation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_cases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigation_cases_title'), ['title'], unique=False)

    op.create_table('iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('threat_level', sa.String(), nullable=True),
    sa.Column('is_watchlist', sa.Boolean(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iocs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_value'), ['value'], unique=False)

    op.create_table('packet_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('dst_ip', sa.String(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('attack_type', sa.String(), nullable=True),
    sa.Column('threat_score', sa.Float(), nullable=True),
    sa.Column('threat_level', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('mail_from', sa.String(length=256), nullable=True),
    sa.Column('rcpt_to', sa.String(length=256), nullable=True),
    sa.Column('email_subject', sa.String(length=512), nullable=True),
    sa.Column('body_len', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('canonical_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('honeypot_id', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('detected_signatures', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packet_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packet_logs_canonical_fingerprint'), ['canonical_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_logs_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_packet_logs_honeypot_id'), ['honeypot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_logs_protocol'), ['protocol'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_logs_src_ip'), ['src_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_logs_threat_level'), ['threat_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_logs_threat_score'), ['threat_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_id'), ['id'], unique=False)

    op.create_table('scheduled_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('template_type', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('schedule_time', sa.String(), nullable=True),
    sa.Column('recipients', sa.String(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reports_name'), ['name'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_json', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('analyst_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_history_id'), ['id'], unique=False)

    op.create_table('sentinel_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playbook_id', sa.String(length=64), nullable=True, comment='Associated playbook ID or NULL for system actions'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='Audit action: approve | reject | regenerate | export | batch_approve | archive'),
    sa.Column('user', sa.String(length=128), nullable=False, comment='Username or service performing the action'),
    sa.Column('details', sa.Text(), nullable=True, comment='JSON string or free text providing action metadata'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='UTC timestamp of the audit event'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentinel_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentinel_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_audit_logs_playbook_id'), ['playbook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('sentinel_playbooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playbook_id', sa.String(length=64), nullable=False, comment='Human-readable unique identifier, e.g. PB-20260617-0001'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='UTC timestamp when the playbook record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='UTC timestamp of last modification; auto-updated on save'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Revision number for this playbook (1 = original, 2+ = regenerated)'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment="FK to the previous version's row ID (NULL for first version)"),
    sa.Column('is_latest', sa.Boolean(), nullable=False, comment='True if this is the most recent version of the playbook lineage'),
    sa.Column('regeneration_reason', sa.String(length=512), nullable=True, comment="Reason for regeneration, e.g. 'Updated threat intelligence' or 'Analyst-requested refresh'"),
    sa.Column('src_ip', sa.String(length=45), nullable=True, comment='Attacker source IP address (IPv4 or IPv6)'),
    sa.Column('dst_port', sa.Integer(), nullable=True, comment='Destination port used to infer honeypot service type'),
    sa.Column('protocol', sa.String(length=16), nullable=True, comment='Network protocol: TCP | UDP | ICMP | IP'),
    sa.Column('attack_type', sa.String(length=128), nullable=True, comment='ML attack classification label, e.g. SSH_AUTH_FAILURE'),
    sa.Column('threat_score', sa.Float(), nullable=True, comment='ML threat confidence score in range 0.0ΓÇô100.0'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='Composite playbook confidence score in range 0.0–1.0. Computed from cluster_size_score, ml_avg_score, ioc_density, and multi_proto_bonus via weighted average in confidence_scoring.py.'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='Dynamic quality score (0-100) based on IOC count, cluster volume, model confidence, and multi-source verification.'),
    sa.Column('severity', sa.String(length=16), nullable=True, comment='Severity tier derived from confidence_score: CRITICAL (>=0.8) | HIGH (>=0.6) | MEDIUM (>=0.4) | LOW (<0.4)'),
    sa.Column('technique_id', sa.String(length=32), nullable=True, comment='MITRE ATT&CK technique ID, e.g. T1110.001'),
    sa.Column('technique_name', sa.String(length=256), nullable=True, comment='MITRE ATT&CK technique name, e.g. Brute Force: Password Guessing'),
    sa.Column('tactic', sa.String(length=128), nullable=True, comment='MITRE ATT&CK tactic name, e.g. Credential Access'),
    sa.Column('mitre_url', sa.String(length=512), nullable=True, comment='Official MITRE ATT&CK technique reference URL'),
    sa.Column('snort_rule', sa.Text(), nullable=True, comment='Generated Snort IDS rule string produced by rule_generator.py'),
    sa.Column('sigma_rule', sa.Text(), nullable=True, comment='Generated Sigma YAML rule (reserved for Phase 6; currently null)'),
    sa.Column('playbook_name', sa.String(length=256), nullable=True, comment='Short human-readable playbook title'),
    sa.Column('playbook_content', sa.Text(), nullable=True, comment='Full rendered playbook body (Markdown format)'),
    sa.Column('template_name', sa.String(length=128), nullable=True, comment='Jinja2 template filename used to render playbook_content'),
    sa.Column('llm_narrative', sa.Text(), nullable=True, comment='AI-generated playbook narrative summary (Markdown format)'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Workflow status: pending | approved | rejected | exported'),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True, comment='Username of the analyst who approved or rejected this playbook'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='UTC timestamp when the analyst reviewed this playbook'),
    sa.ForeignKeyConstraint(['parent_id'], ['sentinel_playbooks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentinel_playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_attack_type'), ['attack_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_dst_port'), ['dst_port'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_is_latest'), ['is_latest'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_playbook_id'), ['playbook_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_src_ip'), ['src_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentinel_playbooks_technique_id'), ['technique_id'], unique=False)

    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sentinel_llm_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_config_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_config_key'), ['key'], unique=True)

    op.create_table('taxii_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('key_id', sa.String(length=36), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('allowed_collections', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxii_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxii_clients_client_name'), ['client_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_taxii_clients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taxii_clients_key_id'), ['key_id'], unique=True)

    op.create_table('traffic_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_packets', sa.Integer(), nullable=True),
    sa.Column('active_connections', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_stats_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('case_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_evidence_id'), ['id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('honeypot_type', sa.String(), nullable=True),
    sa.Column('raw_data', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pcap_path', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attack_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_source_ip'), ['source_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('honeypot_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('honeypot_type', sa.String(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('honeypot_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_honeypot_nodes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_honeypot_nodes_node_id'), ['node_id'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('pcap_captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('packet_count', sa.Integer(), nullable=True),
    sa.Column('protocol_summary', sa.Text(), nullable=True),
    sa.Column('capture_duration', sa.Float(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=True),
    sa.Column('threat_patterns', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pcap_captures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pcap_captures_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pcap_captures_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pcap_captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pcap_captures_id'))
        batch_op.drop_index(batch_op.f('ix_pcap_captures_event_id'))

    op.drop_table('pcap_captures')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('honeypot_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_honeypot_nodes_node_id'))
        batch_op.drop_index(batch_op.f('ix_honeypot_nodes_id'))

    op.drop_table('honeypot_nodes')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_events_source_ip'))
        batch_op.drop_index(batch_op.f('ix_events_session_id'))

    op.drop_table('events')
    with op.batch_alter_table('case_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_evidence_id'))

    op.drop_table('case_evidence')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('traffic_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_stats_id'))

    op.drop_table('traffic_stats')
    with op.batch_alter_table('taxii_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxii_clients_key_id'))
        batch_op.drop_index(batch_op.f('ix_taxii_clients_id'))
        batch_op.drop_index(batch_op.f('ix_taxii_clients_client_name'))

    op.drop_table('taxii_clients')
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_key'))
        batch_op.drop_index(batch_op.f('ix_system_config_id'))
        batch_op.drop_index(batch_op.f('ix_system_config_category'))

    op.drop_table('system_config')
    with op.batch_alter_table('sentinel_playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_technique_id'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_status'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_src_ip'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_severity'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_playbook_id'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_parent_id'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_is_latest'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_id'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_dst_port'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_created_at'))
        batch_op.drop_index(batch_op.f('ix_sentinel_playbooks_attack_type'))

    op.drop_table('sentinel_playbooks')
    with op.batch_alter_table('sentinel_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentinel_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_sentinel_audit_logs_playbook_id'))
        batch_op.drop_index(batch_op.f('ix_sentinel_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_sentinel_audit_logs_action'))

    op.drop_table('sentinel_audit_logs')
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_id'))

    op.drop_table('search_history')
    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_reports_name'))
        batch_op.drop_index(batch_op.f('ix_scheduled_reports_id'))

    op.drop_table('scheduled_reports')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_id'))

    op.drop_table('policies')
    with op.batch_alter_table('packet_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packet_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_packet_logs_threat_score'))
        batch_op.drop_index(batch_op.f('ix_packet_logs_threat_level'))
        batch_op.drop_index(batch_op.f('ix_packet_logs_src_ip'))
        batch_op.drop_index(batch_op.f('ix_packet_logs_protocol'))
        batch_op.drop_index(batch_op.f('ix_packet_logs_id'))
        batch_op.drop_index(batch_op.f('ix_packet_logs_honeypot_id'))
        batch_op.drop_index(batch_op.f('ix_packet_logs_event_id'))
        batch_op.drop_index(batch_op.f('ix_packet_logs_canonical_fingerprint'))

    op.drop_table('packet_logs')
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iocs_value'))
        batch_op.drop_index(batch_op.f('ix_iocs_type'))
        batch_op.drop_index(batch_op.f('ix_iocs_id'))

    op.drop_table('iocs')
    with op.batch_alter_table('investigation_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_cases_title'))
        batch_op.drop_index(batch_op.f('ix_investigation_cases_id'))

    op.drop_table('investigation_cases')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('attack_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attack_sessions_attacker_ip'))

    op.drop_table('attack_sessions')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))
        batch_op.drop_index(batch_op.f('ix_alerts_source_ip'))
        batch_op.drop_index(batch_op.f('ix_alerts_level'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
